"""Background poller: pulls dashboard data from marsh@home on a fixed cadence.

Keeps one in-memory snapshot, refreshed every POLL_INTERVAL_S. Endpoints read
the cached snapshot directly; they never touch the wire. On failure, the last
good snapshot stays available and the error is surfaced via /api/health.
"""

from __future__ import annotations

import asyncio
import re
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import parsers
from ssh_client import ReadOnlySSH


QUEUES: list[tuple[str, str]] = [
    ("gpu", r"C:\dev\hd-instrument\data\overnight_queue"),
    ("cpu", r"C:\dev\hd-instrument\data\remote_cpu_queue"),
]

# Local paths — same machine as the dashboard server; no SSH needed.
_STATUS_LOG_PATH    = Path(r"D:\AI\hd-instrument\data\orchestrator_status_log.jsonl")
_IN_FLIGHT_PATH     = Path(r"D:\AI\hd-instrument\data\orchestrator_in_flight.json")
_QUESTIONS_MD_PATH  = Path(r"D:\AI\hd-instrument\data\orchestrator_questions.md")
_NEWS_ACKS_PATH     = Path(r"D:\AI\hd-instrument\data\orchestrator_news_acks.jsonl")
_ANSWERS_PATH       = Path(r"D:\AI\hd-instrument\data\orchestrator_answers.jsonl")
_LOCAL_CPU_QUEUE_JSON  = Path(r"D:\AI\hd-instrument\data\local_cpu_queue\queue.json")
_LOCAL_CPU_QUEUE_LOG   = Path(r"D:\AI\hd-instrument\data\local_cpu_queue\queue.log")
_LOCAL_CPU_HEARTBEAT   = Path(r"D:\AI\hd-instrument\data\local_cpu_queue\heartbeat.cpu_runner_local.json")
_ROUTING_RATIO_PATH    = Path(r"D:\AI\hd-instrument\data\orchestrator_routing_ratio.json")
# The capability map is generated by the orchestrator on this workstation; remote
# only catches up via git pull and was empirically lagging by 100+ versions
# (v2 served, v189 local at 2026-05-24). Treat local as the source of truth and
# fall back to the remote SFTP read only if the local file is missing.
_LOCAL_CAPABILITY_MAP_PATH = Path(r"D:\AI\hd-instrument\notes\substrate_capability_map.md")
# Remote state cache — populated every 30s by heartbeat_watchdog SCP pull.
# Contains logical_processes: grouped + classified Python process list from the emitter.
_REMOTE_STATE_CACHE_PATH = Path(r"D:\AI\hd-instrument\data\remote_state_cache.json")

# Session heartbeat files — one per session (orchestrator, research, testbed,
# cloud). Each session writes its own; dashboard surfaces freshness + focus.
# See tools/orchestrator/session_heartbeat.py for the writer.
_DATA_DIR = Path(r"D:\AI\hd-instrument\data")
_SESSION_NAMES = ("orchestrator", "research", "testbed", "cloud")

POLL_INTERVAL_S = 3.0
HISTORY_LIMIT = 80
EXP_TAIL_LINES = 8

# Sanity gate on experiment names before interpolating into a remote command.
# Names are alphanumeric + underscore + dash; reject anything else.
_NAME_RE = re.compile(r"^[A-Za-z0-9_\-]+$")


class Poller:
    def __init__(self) -> None:
        self._ssh = ReadOnlySSH()
        self._lock = threading.Lock()
        self.snapshot: dict[str, Any] = {}
        self.last_poll_ok_iso: str | None = None
        self.last_poll_attempted_iso: str | None = None
        self.last_error: str | None = None
        self.poll_count = 0
        self.last_poll_ms: float | None = None
        # Per-queue: previously-seen tail and when it last changed (UTC).
        self._prev_tails: dict[str, list[str]] = {}
        self._tail_change_ts: dict[str, datetime] = {}
        # Cache for on-demand experiment-log tails (name -> (ts, text)).
        self._exp_log_cache: dict[str, tuple[float, str]] = {}
        self._exp_log_cache_lock = threading.Lock()
        # Capability map: last good content + status of most recent fetch attempt.
        self._last_capability_md: str = ""
        self._last_capability_status: str = "unknown"
        self._capability_skip_count: int = 0
        # GPU util EMA — smooths the cell-boundary jitter typical of substrate
        # experiments (short GPU bursts interleaved with CPU prep). alpha=0.10
        # with 3s polls gives ~30s effective window.
        self._gpu_util_ema: float | None = None
        # Last-good heartbeat per queue label — used as a fallback when the
        # current poll returns unparseable (mid-write) JSON, preventing the
        # brief "HEARTBEAT UNREADABLE" flash that would otherwise appear.
        self._last_good_heartbeat: dict[str, dict] = {}

    async def run_forever(self) -> None:
        while True:
            try:
                await asyncio.to_thread(self._poll_once)
            except asyncio.CancelledError:
                raise
            except Exception as e:
                with self._lock:
                    self.last_error = f"{type(e).__name__}: {e}"
            await asyncio.sleep(POLL_INTERVAL_S)

    def _build_cmds(self) -> list[tuple[str, str]]:
        """Build (slot_key, command) pairs. Slot_key lets us reassemble dynamically."""
        cmds: list[tuple[str, str]] = [
            ("nvidia_smi",
             "nvidia-smi --query-gpu=utilization.gpu,memory.used,memory.total,"
             "temperature.gpu --format=csv,noheader,nounits"),
            ("nvidia_compute_apps",
             "nvidia-smi --query-compute-apps=pid,process_name,used_gpu_memory "
             "--format=csv,noheader"),
            ("python_procs", 'tasklist /FI "IMAGENAME eq python.exe"'),
        ]
        prev_runs = self.snapshot.get("runs", {})
        for label, qdir in QUEUES:
            cmds.append((f"{label}_heartbeat", f"type {qdir}\\heartbeat.json"))
            cmds.append((f"{label}_queue", f"type {qdir}\\queue.json"))
            cmds.append((
                f"{label}_log_tail",
                f'powershell -Command "Get-Content {qdir}\\queue.log -Tail 1000"',
            ))
            prev = prev_runs.get(label) or {}
            # Precedence: queue.json is canonical for "what's currently assigned".
            # log_running_name only kicks in if queue.json doesn't have a running
            # entry yet (rare: just-after-START, queue.json not updated yet).
            # heartbeat.current is the laggiest signal (multiple writers race).
            current = (
                prev.get("queue_running_name")
                or prev.get("current")
                or prev.get("log_running_name")
            )
            if current and _NAME_RE.match(current):
                cmds.append((
                    f"{label}_exp_tail",
                    f'powershell -Command "Get-Content {qdir}\\{current}.log -Tail {EXP_TAIL_LINES}"',
                ))
                # progress.json: optional convention; absent files just yield empty.
                cmds.append((
                    f"{label}_progress_json",
                    f"type C:\\dev\\hd-instrument\\data\\exp_{current}\\progress.json",
                ))
        # Tail enough lines to cover the full event history for the registry.
        # ~50 experiments × ~5 events each = ~250 lines today; 1500 gives headroom.
        cmds.append((
            "session_events_tail",
            'powershell -Command "Get-Content '
            'C:\\dev\\hd-instrument\\data\\session_events.jsonl -Tail 1500"',
        ))
        # Diagnostic: list session_events* files in data/ so we can verify the path.
        cmds.append((
            "debug_data_dir",
            'powershell -Command "Get-ChildItem '
            'C:\\dev\\hd-instrument\\data -Filter session_events*.jsonl"',
        ))
        # Diagnostic: list notes/ to confirm whether the file exists yet.
        # (capability_map itself is fetched via SFTP for atomic-read protection;
        # see fetch_capability_map_atomic.)
        cmds.append((
            "debug_notes_dir",
            'powershell -Command "Get-ChildItem '
            'C:\\dev\\hd-instrument\\notes -Filter substrate_capability_map*"',
        ))
        # Diagnostic: find any progress.json files anywhere under data/ so we can
        # discover the convention the helper actually uses.
        cmds.append((
            "debug_progress_files",
            'powershell -Command "Get-ChildItem '
            'C:\\dev\\hd-instrument\\data -Filter progress.json -Recurse"',
        ))
        return cmds

    def _poll_once(self) -> None:
        with self._lock:
            self.last_poll_attempted_iso = datetime.now(timezone.utc).isoformat()
        t0 = time.perf_counter()
        keyed = self._build_cmds()
        results = self._ssh.run_parallel([c for _, c in keyed], tolerate_errors=True)
        # If most commands failed, the SSH transport is likely in a bad state
        # (e.g. channels exhausted). Force-reconnect so the next poll is clean.
        if results and sum(1 for r in results if r is None) > len(results) // 2:
            try:
                self._ssh.reset()
            except Exception:
                pass
        results_by_key = {k: r for (k, _), r in zip(keyed, results)}
        dt = time.perf_counter() - t0

        snap = self._build_snapshot(results_by_key)
        with self._lock:
            self.snapshot = snap
            self.last_poll_ok_iso = datetime.now(timezone.utc).isoformat()
            self.last_error = None
            self.poll_count += 1
            self.last_poll_ms = dt * 1000.0

    def _build_snapshot(self, by_key: dict[str, str | None]) -> dict[str, Any]:
        now = datetime.now(timezone.utc)

        nvidia_out = by_key.get("nvidia_smi") or ""
        compute_apps_out = by_key.get("nvidia_compute_apps") or ""
        procs_out = by_key.get("python_procs") or ""

        per_queue_raw: dict[str, dict] = {}
        per_queue_events: dict[str, list[dict]] = {}
        all_events: list[dict] = []
        for label, _ in QUEUES:
            hb_raw = by_key.get(f"{label}_heartbeat") or ""
            q_raw = by_key.get(f"{label}_queue") or ""
            log_raw = by_key.get(f"{label}_log_tail") or ""
            exp_tail = by_key.get(f"{label}_exp_tail")  # may be None
            # Parse heartbeat with last-good fallback: if JSON parse fails
            # (e.g. mid-write race), use the previous successful parse so the
            # dashboard shows stale-but-valid data instead of "HEARTBEAT UNREADABLE".
            hb_parsed = parsers.safe_json(hb_raw)
            if hb_parsed is not None:
                self._last_good_heartbeat[label] = hb_parsed
            elif label in self._last_good_heartbeat:
                hb_parsed = self._last_good_heartbeat[label]
            per_queue_raw[label] = {
                "heartbeat": hb_parsed,
                "queue": parsers.safe_json(q_raw),
                "log_raw": log_raw,
                "exp_tail": exp_tail,
            }
            events_this = parsers.parse_queue_log(log_raw, label)
            events_this.sort(key=lambda e: e["ts"], reverse=True)
            per_queue_events[label] = events_this
            all_events.extend(events_this)

        proc_list = parsers.parse_python_procs(procs_out)
        running_pids = {p["pid"] for p in proc_list}
        total_mem_kb = sum(p.get("mem_kb") or 0 for p in proc_list)

        gpu_apps_all = parsers.parse_nvidia_compute_apps(compute_apps_out)
        # Filter to python procs. On Windows WDDM, this query also surfaces desktop
        # processes (dwm.exe, explorer.exe) with 0 MiB — useless noise for our purpose.
        gpu_apps = [a for a in gpu_apps_all if "python" in (a.get("name") or "").lower()]
        gpu_apps_by_pid = {a["pid"]: a for a in gpu_apps}
        gpu_procs_total_mib = sum(a.get("gpu_mem_mib") or 0 for a in gpu_apps)

        runs: dict[str, dict] = {}
        queue_view: dict[str, dict] = {}
        for label, qdir in QUEUES:
            hb = per_queue_raw[label]["heartbeat"]
            qd = per_queue_raw[label]["queue"]
            state = parsers.derive_run_state(label, hb, qd, now)
            try:
                pid = int(state.get("pid")) if state.get("pid") is not None else None
            except (TypeError, ValueError):
                pid = None
            pid_alive = (pid in running_pids) if pid is not None else None
            state["pid_alive"] = pid_alive
            state["queue_dir"] = qdir.rsplit("\\", 1)[-1]
            # Trust queue.json's running flag. If queue.json says nothing's running,
            # don't promote a stale log START to "current" — that's a crashed/orphaned
            # run, not an active one. queue.json is the canonical source of truth.
            if state.get("queue_marks_running"):
                state["log_running_name"] = parsers.find_running_from_log(per_queue_events[label])
            else:
                state["log_running_name"] = None
            tail_raw = per_queue_raw[label]["exp_tail"]
            cur_tail = tail_raw.splitlines()[-EXP_TAIL_LINES:] if tail_raw else []
            state["stdout_tail"] = cur_tail

            # Track log-file freshness via tail-change detection across polls.
            tail_age_s: float | None = None
            if cur_tail:
                prev = self._prev_tails.get(label)
                if prev != cur_tail:
                    self._tail_change_ts[label] = now
                self._prev_tails[label] = cur_tail
            change_ts = self._tail_change_ts.get(label)
            if change_ts is not None:
                tail_age_s = (now - change_ts).total_seconds()
            state["tail_age_s"] = round(tail_age_s, 1) if tail_age_s is not None else None

            severity, message = parsers.compute_severity(state, pid_alive, tail_age_s)
            state["severity"] = severity
            state["warning"] = message

            # Progress estimate for the running experiment (historical mean → timeout fallback).
            running_name = (
                state.get("queue_running_name")
                or state.get("current")
                or state.get("log_running_name")
            )
            elapsed = state.get("elapsed_s")
            # Fallback: if elapsed_s is missing, derive from the queue.log START ts.
            if elapsed is None and running_name:
                for ev in reversed(per_queue_events[label]):
                    if ev.get("name") == running_name and ev.get("event") == "START":
                        start_dt = parsers.parse_iso_local(ev.get("ts", ""))
                        if start_dt is not None:
                            elapsed = (now - start_dt).total_seconds()
                            state["elapsed_s"] = round(elapsed, 1)
                        break
            if running_name and elapsed is not None and elapsed >= 0:
                expected, source = parsers.estimate_expected_wall_s(
                    running_name, per_queue_events[label], qd
                )
                if expected and expected > 0:
                    state["expected_wall_s"] = round(expected, 1)
                    state["expected_wall_source"] = source
                    state["progress_pct"] = min(99.0, round((elapsed / expected) * 100, 1))
                    state["progress_source"] = source  # "historical" or "timeout"

            # progress.json (optional): if the experiment writes one, prefer cell-based
            # progress over the wall-time heuristic. Schema:
            #   {phase: str, cell: int, total_cells: int, eta_sec: int, updated_at: iso}
            prog_raw = by_key.get(f"{label}_progress_json")
            if prog_raw:
                prog = parsers.safe_json(prog_raw)
                if isinstance(prog, dict):
                    state["progress_json"] = prog
                    cell = prog.get("cell")
                    total = prog.get("total_cells")
                    if (isinstance(cell, (int, float))
                            and isinstance(total, (int, float)) and total > 0):
                        state["progress_pct"] = min(99.9, round((cell / total) * 100, 1))
                        state["progress_source"] = "cell"
                    eta = prog.get("eta_sec")
                    if isinstance(eta, (int, float)) and eta >= 0:
                        state["eta_sec"] = round(eta)
            runs[label] = state
            queue_view[label] = {
                "queue_dir": qdir.rsplit("\\", 1)[-1],
                "counts": parsers.queue_counts(qd),
                "pending": parsers.queue_pending(qd),
            }

        all_events.sort(key=lambda e: e["ts"], reverse=True)
        history = all_events[:HISTORY_LIMIT]

        events_raw = by_key.get("session_events_tail") or ""
        events = parsers.parse_event_log(events_raw)
        events.sort(key=lambda e: e.get("ts", ""), reverse=True)

        experiments = parsers.build_experiment_registry(events, per_queue_events)

        # Capability map: prefer the LOCAL file (orchestrator writes here; remote
        # only catches up via git pull and was empirically lagging 100+ versions).
        # Fall back to remote SFTP read if local is missing.
        cap_content, cap_status = self.fetch_capability_map_local_first()
        if cap_status.startswith("ok") and cap_content is not None:
            self._last_capability_md = cap_content
            self._capability_skip_count = 0
        elif cap_status in ("mid_rename", "changing"):
            self._capability_skip_count += 1
            # Keep last good content; status surfaces the skip.
        elif cap_status == "missing":
            self._last_capability_md = ""
        # error:* and other states: keep last good content silently.
        self._last_capability_status = cap_status

        # Per-line parse diagnostic: try parsing the first 5 non-empty lines explicitly.
        import json as _json
        _lines = events_raw.splitlines()
        _line_count = len(_lines)
        _parse_successes = 0
        _parse_errors: list[dict] = []
        _checked = 0
        for _i, _line in enumerate(_lines):
            _s = _line.strip()
            if not _s:
                continue
            _checked += 1
            if _checked > 5:
                break
            try:
                _json.loads(_s)
                _parse_successes += 1
            except Exception as _e:
                _parse_errors.append({
                    "line_idx": _i,
                    "error": f"{type(_e).__name__}: {_e}",
                    "raw_first_80": repr(_s[:80]),
                })

        debug_info = {
            "session_events_tail_chars": len(events_raw),
            "session_events_line_count": _line_count,
            "session_events_events_parsed": len(events),
            "session_events_first5_parse_ok": _parse_successes,
            "session_events_first5_parse_errors": _parse_errors,
            "session_events_tail_head_500": events_raw[:500] if events_raw else "(empty)",
            "data_dir_listing": by_key.get("debug_data_dir") or "(no result)",
            "nvidia_smi_raw": (by_key.get("nvidia_smi") or "")[:300] or "(empty)",
            "nvidia_compute_apps_raw": (by_key.get("nvidia_compute_apps") or "")[:300] or "(empty)",
            "capability_map_chars": len(self._last_capability_md),
            "capability_status": self._last_capability_status,
            "capability_skip_count": self._capability_skip_count,
            "notes_dir_listing": by_key.get("debug_notes_dir") or "(no result)",
            "progress_files_found": by_key.get("debug_progress_files") or "(none)",
        }

        system = parsers.parse_nvidia_smi(nvidia_out)

        # GPU util EMA: smooth the bursty/jittery raw signal. Skip update if the
        # raw read failed this poll (None) so we don't decay artificially.
        cur_util = system.get("util_pct")
        if cur_util is not None:
            try:
                cur_f = float(cur_util)
                EMA_ALPHA = 0.10
                if self._gpu_util_ema is None:
                    self._gpu_util_ema = cur_f
                else:
                    self._gpu_util_ema = EMA_ALPHA * cur_f + (1.0 - EMA_ALPHA) * self._gpu_util_ema
            except (TypeError, ValueError):
                pass
        if self._gpu_util_ema is not None:
            system["util_pct_ema"] = round(self._gpu_util_ema, 1)

        system["python_proc_count"] = len(running_pids)
        system["python_proc_mem_mb"] = round(total_mem_kb / 1024.0, 0) if total_mem_kb else 0
        system["gpu_proc_count"] = len(gpu_apps)
        system["gpu_proc_mem_mib"] = gpu_procs_total_mib
        system["gpu_proc_total_all_apps"] = len(gpu_apps_all)  # diagnostic: WDDM noise count

        # Logical process classification from remote_state_cache (populated by emitter via SCP).
        # Groups venv-shim+interpreter pairs and classifies as runner/emitter/experiment_child.
        logical_procs: list[dict] = []
        logical_procs_ts: str = ""
        try:
            if _REMOTE_STATE_CACHE_PATH.is_file():
                cache_doc = parsers.safe_json(
                    _REMOTE_STATE_CACHE_PATH.read_text(encoding="utf-8", errors="replace")
                )
                if isinstance(cache_doc, dict):
                    lp = cache_doc.get("logical_processes")
                    if isinstance(lp, list):
                        logical_procs = lp
                    logical_procs_ts = cache_doc.get("snapshot_ts", "")
        except Exception:
            pass
        system["logical_processes"] = logical_procs
        system["logical_processes_ts"] = logical_procs_ts
        # Summary counts for quick rendering
        system["logical_runner_count"] = sum(1 for p in logical_procs if p.get("type") == "runner")
        system["logical_emitter_count"] = sum(1 for p in logical_procs if p.get("type") == "emitter")
        system["logical_experiment_count"] = sum(1 for p in logical_procs if p.get("type") == "experiment_child")

        # Cross-reference with active runner PIDs to surface orphan GPU contexts.
        active_runner_pids: set[int] = set()
        for label, _ in QUEUES:
            r_pid_raw = (runs.get(label) or {}).get("pid")
            if r_pid_raw:
                try:
                    active_runner_pids.add(int(r_pid_raw))
                except (TypeError, ValueError):
                    pass

        gpu_procs_list = [
            {
                "pid": a["pid"],
                "name": a.get("name") or "",
                "gpu_mem_mib": a.get("gpu_mem_mib") or 0,
                "is_runner": a["pid"] in active_runner_pids,
            }
            for a in gpu_apps
        ]
        gpu_procs_list.sort(key=lambda a: (a["gpu_mem_mib"] or 0, a["pid"]), reverse=True)
        system["gpu_procs"] = gpu_procs_list
        system["active_runner_count"] = len(active_runner_pids)
        system["unknown_gpu_pids"] = [p["pid"] for p in gpu_procs_list if not p["is_runner"]]
        # Trigger UI when GPU contexts outnumber active runners (per the user's spec).
        system["show_unknown_chips"] = len(gpu_procs_list) > len(active_runner_pids)
        system["idle_python_proc_count"] = max(0, len(running_pids) - len(gpu_apps_by_pid))

        # Discover ad-hoc runs — experiments writing progress.json that the queue
        # runners don't know about. Surfaces direct/manual experiment invocations.
        exp_dirs_with_progress = parsers.parse_progress_dir_listing(
            by_key.get("debug_progress_files") or ""
        )
        ad_hoc_all = self.fetch_ad_hoc_progress(exp_dirs_with_progress, freshness_s=300.0)
        # Drop names that are already tracked by a queue's current.
        tracked_names = set()
        for label in runs:
            for k in ("log_running_name", "current", "queue_running_name"):
                v = runs[label].get(k)
                if v:
                    tracked_names.add(v)
        ad_hoc_runs = [a for a in ad_hoc_all if a["name"] not in tracked_names]

        # Orchestrator status log: local file read (no SSH — same machine as dashboard).
        # Read the last 1000 lines to keep memory bounded while ensuring all acked
        # items remain visible in the window (prevents acked items from being pushed
        # out of the truncation window and reappearing as unread). At ~100 bytes/line
        # this is ~100 KB — negligible.
        status_log_raw = ""
        try:
            if _STATUS_LOG_PATH.is_file():
                lines = _STATUS_LOG_PATH.read_text(encoding="utf-8", errors="replace").splitlines()
                status_log_raw = "\n".join(lines[-1000:])
        except Exception:
            pass
        status_log: list[dict] = []
        if status_log_raw:
            status_log = parsers.parse_status_log(status_log_raw)

        # In-flight dispatches: local JSON read.
        in_flight: dict = {"dispatches": []}
        try:
            if _IN_FLIGHT_PATH.is_file():
                in_flight_raw = _IN_FLIGHT_PATH.read_text(encoding="utf-8", errors="replace")
                in_flight = parsers.parse_in_flight(in_flight_raw)
        except Exception:
            pass

        # Orchestrator questions: local markdown read.
        questions_raw = ""
        orchestrator_questions: list[dict] = []
        try:
            if _QUESTIONS_MD_PATH.is_file():
                questions_raw = _QUESTIONS_MD_PATH.read_text(encoding="utf-8", errors="replace")
                orchestrator_questions = parsers.parse_questions_md(questions_raw)
        except Exception:
            pass

        # Per-session heartbeats: local file reads (one per active session).
        # Each session writes data/session_heartbeat_<session>.json on substantive
        # activity. Dashboard surfaces "alive (current focus)" vs "stale" per session.
        sessions_map: dict = {}
        for sess in _SESSION_NAMES:
            hb_path = _DATA_DIR / f"session_heartbeat_{sess}.json"
            if not hb_path.is_file():
                continue
            try:
                entry = parsers.safe_json(hb_path.read_text(encoding="utf-8", errors="replace"))
            except Exception:
                entry = None
            if not isinstance(entry, dict):
                continue
            hb_ts = parsers.parse_iso_local(entry.get("ts", ""))
            stale_after = int(entry.get("stale_after_s") or 3600)
            age_s = (now - hb_ts).total_seconds() if hb_ts else None
            is_stale = age_s is not None and age_s > stale_after
            sessions_map[sess] = {
                "session": sess,
                "ts": entry.get("ts"),
                "current_focus": entry.get("current_focus") or "",
                "last_event_ts": entry.get("last_event_ts"),
                "stale_after_s": stale_after,
                "age_s": round(age_s, 1) if age_s is not None else None,
                "is_stale": bool(is_stale),
            }

        # Tier summary: derived from the already-fetched capability map.
        tier_summary = parsers.extract_tier_summary(self._last_capability_md)
        # Structured per-row payload for the redesigned Capability tab UI.
        capability_rows = parsers.extract_capability_rows(self._last_capability_md)
        # Version + key metrics (framework reliability, Tier-1 P) for the cap tab header.
        cap_version_meta = parsers.extract_cap_version_meta(self._last_capability_md)

        # ---- Local CPU queue (local filesystem; no SSH) ----
        local_cpu_view: dict = {}
        local_cpu_runs: dict = {}
        local_cpu_queue_doc: dict | None = None
        try:
            if _LOCAL_CPU_QUEUE_JSON.is_file():
                local_cpu_queue_doc = parsers.safe_json(
                    _LOCAL_CPU_QUEUE_JSON.read_text(encoding="utf-8", errors="replace")
                )
        except Exception:
            local_cpu_queue_doc = None
        if local_cpu_queue_doc:
            counts = parsers.queue_counts(local_cpu_queue_doc)
            pending = parsers.queue_pending(local_cpu_queue_doc)
            local_cpu_view = {
                "queue_dir": "local_cpu_queue",
                "counts": counts,
                "pending": pending,
            }
            # Heartbeat for local CPU runner.
            local_hb_doc: dict | None = None
            try:
                if _LOCAL_CPU_HEARTBEAT.is_file():
                    local_hb_doc = parsers.safe_json(
                        _LOCAL_CPU_HEARTBEAT.read_text(encoding="utf-8", errors="replace")
                    )
            except Exception:
                local_hb_doc = None
            state = parsers.derive_run_state("local_cpu", local_hb_doc, local_cpu_queue_doc, now)
            state["queue_dir"] = "local_cpu_queue"
            severity, message = parsers.compute_severity(state, None, None)
            state["severity"] = severity
            state["warning"] = message
            local_cpu_runs = state

        # Merge local CPU into queue_view + runs.
        if local_cpu_view:
            queue_view["local_cpu"] = local_cpu_view
        if local_cpu_runs:
            runs["local_cpu"] = local_cpu_runs

        # ---- Build a unified experiments view from queue docs (replaces the
        # stale registry-built list for the Experiments tab). Each entry:
        # {name, status, verdict?, elapsed_s, queue_dir}. We DO NOT clobber
        # the session-events `experiments` list — that's still useful for the
        # capability-tab cross-link lookup. We add `queue_experiments` as a
        # fresh, queue-doc-derived list. ----
        queue_experiments: list[dict] = []

        def _push_from_queue_doc(doc: dict | None, queue_dir_name: str) -> None:
            if not doc:
                return
            for e in doc.get("experiments", []):
                if not isinstance(e, dict):
                    continue
                started = e.get("started_at")
                ended = e.get("ended_at") or e.get("completed_at")
                elapsed: float | None = e.get("wall_s")
                if elapsed is None and started:
                    try:
                        s_dt = parsers.parse_iso_local(started)
                        e_dt = parsers.parse_iso_local(ended) if ended else now
                        if s_dt is not None and e_dt is not None:
                            elapsed = (e_dt - s_dt).total_seconds()
                    except Exception:
                        pass
                queue_experiments.append({
                    "name": e.get("name", ""),
                    "status": (e.get("status") or "").lower(),
                    "purpose": e.get("purpose", ""),
                    "started_at": started,
                    "ended_at": ended,
                    "elapsed_s": round(elapsed, 1) if isinstance(elapsed, (int, float)) else None,
                    "queue_dir": queue_dir_name,
                    "note": e.get("note", ""),
                    "exit_code": e.get("exit_code"),
                    "timeout_s": e.get("timeout_s"),
                })

        for label, _ in QUEUES:
            qd_name = "overnight_queue" if label == "gpu" else "remote_cpu_queue"
            _push_from_queue_doc(per_queue_raw[label].get("queue"), qd_name)
        _push_from_queue_doc(local_cpu_queue_doc, "local_cpu_queue")

        # Sort newest activity first; pending appear at top within their queue cluster.
        def _exp_sort_key(e: dict) -> tuple:
            # running > pending > completed/failed; within group, newest activity first.
            s = e.get("status") or ""
            rank = {"running": 0, "pending": 1, "queued": 1, "claimed": 1}.get(s, 2)
            ts = e.get("ended_at") or e.get("started_at") or ""
            return (rank, "" if rank < 2 else ts)
        # Sort: rank ascending; for completed group, ts descending (newest first).
        running_pending = [e for e in queue_experiments if e.get("status") in ("running", "pending", "queued", "claimed")]
        completed = [e for e in queue_experiments if e.get("status") not in ("running", "pending", "queued", "claimed")]
        completed.sort(key=lambda e: e.get("ended_at") or e.get("started_at") or "", reverse=True)
        # Show full ledger; the Experiments tab paginates / filters client-side.
        queue_experiments = running_pending + completed

        # ---- News acks + news items ----
        acked_ids: set[str] = set()
        try:
            if _NEWS_ACKS_PATH.is_file():
                acked_ids = parsers.parse_acks(
                    _NEWS_ACKS_PATH.read_text(encoding="utf-8", errors="replace")
                )
        except Exception:
            pass
        news_items = parsers.derive_news_items(status_log, acked_ids, limit=30)

        # ---- Answers (for diagnostics; orchestrator consumes via dispatch.py) ----
        answers: list[dict] = []
        try:
            if _ANSWERS_PATH.is_file():
                answers = parsers.parse_answers(
                    _ANSWERS_PATH.read_text(encoding="utf-8", errors="replace")
                )
        except Exception:
            pass

        # Filter out questions that already have an answer recorded.
        answered_qnums = {a.get("question_number") for a in answers if a.get("question_number") is not None}
        open_questions = [q for q in orchestrator_questions if q.get("number") not in answered_qnums]

        # Orchestrator health: routing-ratio snapshot (written by
        # tools/orchestrator/routing_ratio.py). Reconnaissance read of a
        # JSON blob — null if not yet computed.
        routing_ratio_doc: dict | None = None
        try:
            if _ROUTING_RATIO_PATH.is_file():
                routing_ratio_doc = parsers.safe_json(
                    _ROUTING_RATIO_PATH.read_text(encoding="utf-8", errors="replace")
                )
        except Exception:
            routing_ratio_doc = None

        debug_info["status_log_entries"] = len(status_log)
        debug_info["status_log_raw_chars"] = len(status_log_raw)
        debug_info["tier_summary_parse_ok"] = tier_summary.get("parse_ok", False)
        debug_info["in_flight_count"] = len(in_flight.get("dispatches", []))
        debug_info["questions_count"] = len(open_questions)
        debug_info["news_acks_count"] = len(acked_ids)
        debug_info["news_items_count"] = len(news_items)
        debug_info["answers_count"] = len(answers)
        debug_info["queue_experiments_count"] = len(queue_experiments)
        debug_info["local_cpu_queue_present"] = local_cpu_queue_doc is not None

        # recent_verdicts: top-20 experiments with a verdict, newest outcome first.
        # Mirrors the local_dashboard_snapshot.json schema so dispatch.py / any
        # poller-aware consumer sees the same shape from both sources.
        recent_verdicts: list[dict] = [
            {
                "name": e.get("name", ""),
                "verdict": e.get("verdict", ""),
                "verdict_msg": e.get("outcome_summary", ""),
                "elapsed_s": e.get("wall_s"),
                "outcome_at": e.get("outcome_at", ""),
            }
            for e in experiments
            if e.get("verdict")
        ]
        recent_verdicts.sort(key=lambda v: v.get("outcome_at") or "", reverse=True)
        recent_verdicts = recent_verdicts[:20]

        debug_info["recent_verdicts_count"] = len(recent_verdicts)

        return {
            "ts": now.isoformat(),
            "system": system,
            "runs": runs,
            "queue": queue_view,
            "history": history,
            "events": events,
            "experiments": experiments,
            "queue_experiments": queue_experiments,
            "recent_verdicts": recent_verdicts,
            "capability_map": self._last_capability_md,
            "capability_status": self._last_capability_status,
            "capability_skip_count": self._capability_skip_count,
            "status_log": status_log,
            "tier_summary": tier_summary,
            "capability_rows": capability_rows,
            "cap_version_meta": cap_version_meta,
            "ad_hoc_runs": ad_hoc_runs,
            "in_flight": in_flight,
            "orchestrator_questions": open_questions,
            "orchestrator_questions_raw": questions_raw,
            "news_items": news_items,
            "news_acks_count": len(acked_ids),
            "answers_count": len(answers),
            "orchestrator_health": routing_ratio_doc,
            "sessions": sessions_map,
            "_debug": debug_info,
        }

    def fetch_ad_hoc_progress(self, exp_dirs: list[str], freshness_s: float = 300.0) -> list[dict]:
        """Read progress.json from each given dir; keep only files modified within
        freshness_s seconds. Used to surface ad-hoc runs not tracked by queue.json.

        Returns list of {name, progress_json, file_age_s, mtime}.
        """
        out: list[dict] = []
        now = time.time()
        for dir_path in exp_dirs:
            prog_path = f"{dir_path}\\progress.json"
            try:
                st = self._ssh.sftp_stat(prog_path)
                age_s = now - st.st_mtime
                if age_s > freshness_s:
                    continue
                content = self._ssh.sftp_read_text(prog_path, encoding="utf-8")
            except Exception:
                continue
            prog = parsers.safe_json(content)
            if not isinstance(prog, dict):
                continue
            sub = dir_path.rsplit("\\", 1)[-1]
            name = sub[4:] if sub.startswith("exp_") else sub
            out.append({
                "name": name,
                "progress_json": prog,
                "file_age_s": round(age_s, 1),
                "mtime": st.st_mtime,
            })
        out.sort(key=lambda x: x.get("mtime") or 0, reverse=True)
        return out

    def fetch_capability_map_local_first(self) -> tuple[str | None, str]:
        """Read the capability map, preferring the LOCAL workstation file.

        The orchestrator writes notes/substrate_capability_map.md on this
        workstation (D:\\AI\\hd-instrument\\notes\\). The remote machine
        (marsh@home, C:\\dev\\hd-instrument\\notes\\) only catches up via
        `git pull` and was empirically lagging 100+ versions (e.g. dashboard
        served v2/v3 from remote while local sat at v189). The fix: read the
        local file first. Fall back to the remote SFTP read only when the
        local file is missing.

        Returns (content_or_None, status). Status values:
          'ok:local'    - clean local read (preferred path)
          'ok:remote'   - local missing, remote SFTP read succeeded
          plus all status strings from fetch_capability_map_atomic when we fall through.
        """
        try:
            if _LOCAL_CAPABILITY_MAP_PATH.is_file():
                content = _LOCAL_CAPABILITY_MAP_PATH.read_text(
                    encoding="utf-8", errors="replace"
                )
                return content, "ok:local"
        except (OSError, IOError):
            # Local read raced; fall through to remote so we don't drop the panel.
            pass

        remote_content, remote_status = self.fetch_capability_map_atomic()
        if remote_status == "ok" and remote_content is not None:
            return remote_content, "ok:remote"
        return remote_content, remote_status

    def fetch_capability_map_atomic(self) -> tuple[str | None, str]:
        """Read notes/substrate_capability_map.md with mid-write protection.

        Returns (content_or_None, status). Status values:
          'ok'         - clean read, content is current
          'mid_rename' - tempfile present in notes/, skip this poll
          'changing'   - file mtime changed before/after read AND retry; skip
          'missing'    - file does not exist
          'error:...'  - SFTP or path error
        """
        notes_dir = r"C:\dev\hd-instrument\notes"
        target_name = "substrate_capability_map.md"
        target_path = f"{notes_dir}\\{target_name}"

        try:
            entries = self._ssh.sftp_listdir(notes_dir)
        except Exception as e:
            return None, f"error:listdir:{type(e).__name__}"

        target_lower = target_name.lower()
        related = [
            f for f in entries
            if f.lower().startswith(target_lower)
            or (target_lower in f.lower() and (
                f.endswith(".tmp") or f.endswith(".swp") or f.endswith("~")
                or f.startswith(".") or ".tmp." in f.lower()
            ))
        ]
        if target_name not in entries:
            return None, "missing"
        if len(related) > 1:
            return None, "mid_rename"

        try:
            st1 = self._ssh.sftp_stat(target_path)
            content = self._ssh.sftp_read_text(target_path, encoding="utf-8")
            st2 = self._ssh.sftp_stat(target_path)
        except Exception as e:
            return None, f"error:read:{type(e).__name__}"

        if st1.st_mtime != st2.st_mtime or st1.st_size != st2.st_size:
            # File changed during read — retry once.
            try:
                content = self._ssh.sftp_read_text(target_path, encoding="utf-8")
                st3 = self._ssh.sftp_stat(target_path)
            except Exception as e:
                return None, f"error:retry:{type(e).__name__}"
            if st2.st_mtime != st3.st_mtime or st2.st_size != st3.st_size:
                return None, "changing"

        return content, "ok"

    def fetch_exp_log_tail(self, name: str, queue_dir: str, lines: int = 30) -> str:
        """On-demand fetch of <queue_dir>/<name>.log tail. Cached for 60s."""
        if not _NAME_RE.match(name):
            return ""
        if queue_dir not in ("overnight_queue", "remote_cpu_queue"):
            return ""
        cache_key = f"log:{queue_dir}/{name}/{lines}"
        now = time.time()
        with self._exp_log_cache_lock:
            cached = self._exp_log_cache.get(cache_key)
            if cached and now - cached[0] < 60.0:
                return cached[1]
        qdir_full = rf"C:\dev\hd-instrument\data\{queue_dir}"
        cmd = (
            f'powershell -Command "Get-Content {qdir_full}\\{name}.log '
            f'-Tail {lines}"'
        )
        try:
            results = self._ssh.run_parallel([cmd], tolerate_errors=True)
            text = results[0] if results and results[0] else ""
        except Exception:
            text = ""
        with self._exp_log_cache_lock:
            self._exp_log_cache[cache_key] = (now, text)
        return text

    def fetch_exp_metrics(self, name: str) -> str:
        """On-demand fetch of data/exp_<name>/metrics.json. Cached for 60s."""
        if not _NAME_RE.match(name):
            return ""
        cache_key = f"metrics:{name}"
        now = time.time()
        with self._exp_log_cache_lock:
            cached = self._exp_log_cache.get(cache_key)
            if cached and now - cached[0] < 60.0:
                return cached[1]
        path = rf"C:\dev\hd-instrument\data\exp_{name}\metrics.json"
        cmd = f"type {path}"
        try:
            results = self._ssh.run_parallel([cmd], tolerate_errors=True)
            text = results[0] if results and results[0] else ""
        except Exception:
            text = ""
        with self._exp_log_cache_lock:
            self._exp_log_cache[cache_key] = (now, text)
        return text

    def close(self) -> None:
        self._ssh.close()

    def health(self) -> dict[str, Any]:
        with self._lock:
            return {
                "last_poll_ok": self.last_poll_ok_iso,
                "last_poll_attempted": self.last_poll_attempted_iso,
                "last_error": self.last_error,
                "poll_count": self.poll_count,
                "last_poll_ms": round(self.last_poll_ms, 1) if self.last_poll_ms else None,
                "poll_interval_s": POLL_INTERVAL_S,
            }

    def get_snapshot(self) -> dict[str, Any]:
        with self._lock:
            return dict(self.snapshot)
