"""Substrate-native deterministic-hash token vocabulary + codebook (Path C).

Manages a token -> id -> bipolar hypervector codebook for substrate-native
language ingest. Path C discipline: codebook entries are CONTENT-FREE random
sparse-bipolar vectors generated by deterministic hash-seeded RNG; semantic
content lives in the W / S accumulators downstream, NEVER in the basis vectors.

Composition:
  - Reuses the `_bipolar_hv` / `_seed_for_trigram` pattern from
    hdlab.char_trigram_encoder (chain-grade text encoder primitive). The
    difference is the hash input: whole token instead of trigram.
  - Codebook matrix shape [V_TOK + 1, N_DIM] (extra slot for <UNK>).
  - Persists vocabulary to JSONL at `data/substrate_index/lang/tokens.jsonl`
    (one atom per token; metadata.codebook_seed = blake2b hash).

ENCODER_PROVENANCE = "SUBSTRATE_NATIVE" per Path C META rule (R3 fix discipline:
no Pythia / MiniLM / word2vec at encode-side; basis is random; semantics emerge
from binding + Hebbian accumulation downstream).

Discipline notes:
  - blake2b digest_size=8 (64-bit seed) chosen so that at V_TOK ~ 4B tokens
    the birthday-bound collision probability remains ~0.5 (vs digest_size=4
    which collides at ~65k tokens; see Section 3.2 of drill 3 research note).
  - Vocabulary growth is monotone-deterministic: re-adding the same token is
    a no-op; new tokens always get new ids appended (no re-mapping). `freeze()`
    locks growth as required before publishing chain-grade cell.
  - All randomness flows through the per-token blake2b seed; one optional
    `seed` constructor arg salts the hash for ablation cells (changes the
    basis entirely; semantic geometry stays equivalent in expectation).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Iterable

import numpy as np

ENCODER_PROVENANCE: str = "SUBSTRATE_NATIVE"

# Defaults per substrate-product convention. drill 3 ANCHOR_1 uses
# V_TOK = 8192 / N_DIM = 8192 (raised from prior 4096; substrate-product
# convention 2026-06-26).
N_DIM_DEFAULT: int = 8192
V_MAX_DEFAULT: int = 50_000

UNK_TOKEN: str = "<UNK>"
BOS_TOKEN: str = "<BOS>"
EOS_TOKEN: str = "<EOS>"


def _seed_for_token(token: str, salt: int = 0) -> int:
    """64-bit deterministic seed for `token`; `salt` lets ablation cells re-basis.

    Returns: int in [0, 2**64). Uses blake2b digest_size=8 so 4B-token regime
    has birthday-collision prob ~0.5 (vs 65k with digest_size=4).
    """
    h = hashlib.blake2b(
        token.encode("utf-8"),
        digest_size=8,
        salt=salt.to_bytes(8, "big") if salt else b"",
    ).digest()
    return int.from_bytes(h, "big")


def _bipolar_hv(seed: int, n_dim: int) -> np.ndarray:
    """Bipolar {-1, +1} hypervector, shape [n_dim]; deterministic from `seed`."""
    rng = np.random.default_rng(seed & 0xFFFFFFFFFFFFFFFF)
    return (rng.integers(0, 2, size=n_dim) * 2 - 1).astype(np.float32)


class TokenVocab:
    """Deterministic-hash token vocabulary + bipolar codebook (Path C).

    Maps strings <-> int ids; ids index a `[V + 1, N_DIM]` bipolar codebook
    (last row = UNK). Codebook entries are generated lazily on first request
    and cached. Vocabulary growth is monotone; `freeze()` locks it before
    chain-grade reporting.

    Use `build_from_corpus(tokens, v_top)` to seed from a stream by frequency,
    OR `add_token(s)` to grow incrementally.
    """

    def __init__(
        self,
        n_dim: int = N_DIM_DEFAULT,
        v_max: int = V_MAX_DEFAULT,
        seed: int = 0,
    ) -> None:
        """Init empty vocab; `seed` salts the hash basis for ablation cells."""
        self.n_dim: int = int(n_dim)
        self.v_max: int = int(v_max)
        self.seed: int = int(seed)
        self._token_to_id: dict[str, int] = {}
        self._id_to_token: list[str] = []
        self._frequency: list[int] = []
        self._codebook_cache: dict[int, np.ndarray] = {}
        self._unk_hv: np.ndarray | None = None
        self._frozen: bool = False
        self._provenance: str = ENCODER_PROVENANCE

    # ---- inspection ----
    def __len__(self) -> int:
        """# tokens in vocabulary (excluding UNK)."""
        return len(self._id_to_token)

    @property
    def v_tok(self) -> int:
        """Current vocabulary size (excluding UNK)."""
        return len(self._id_to_token)

    @property
    def unk_id(self) -> int:
        """UNK id; always == v_tok (last slot in codebook matrix)."""
        return self.v_tok

    @property
    def frozen(self) -> bool:
        """True after freeze(); further growth raises."""
        return self._frozen

    @property
    def provenance(self) -> str:
        """ENCODER_PROVENANCE = SUBSTRATE_NATIVE (Path C compliance marker)."""
        return self._provenance

    # ---- core token <-> id ----
    def token_to_id(self, token: str) -> int:
        """Return id of `token`; returns `unk_id` if not in vocab."""
        return self._token_to_id.get(token, self.unk_id)

    def id_to_token(self, idx: int) -> str:
        """Inverse of token_to_id; idx == unk_id returns UNK_TOKEN."""
        if idx == self.unk_id:
            return UNK_TOKEN
        if not (0 <= idx < self.v_tok):
            raise IndexError(f"id {idx} out of range [0, {self.v_tok})")
        return self._id_to_token[idx]

    def add_token(self, token: str, frequency: int = 1) -> int:
        """Add `token` to vocab if absent; bump frequency if present. Returns id.

        Raises RuntimeError if vocab is frozen and token is new. Raises
        ValueError if vocab is at v_max capacity.
        """
        existing = self._token_to_id.get(token)
        if existing is not None:
            self._frequency[existing] += int(frequency)
            return existing
        if self._frozen:
            raise RuntimeError(
                f"vocab is frozen; cannot add new token '{token}'. "
                f"call before freeze() or re-init unfrozen vocab."
            )
        if self.v_tok >= self.v_max:
            raise ValueError(
                f"vocab at capacity v_max={self.v_max}; "
                f"raise v_max or build a fresh vocab."
            )
        new_id = self.v_tok
        self._token_to_id[token] = new_id
        self._id_to_token.append(token)
        self._frequency.append(int(frequency))
        return new_id

    # ---- codebook ----
    def id_to_codebook_vec(self, idx: int) -> np.ndarray:
        """Return bipolar [n_dim] HV for id `idx`. UNK has its own deterministic HV."""
        if idx == self.unk_id:
            if self._unk_hv is None:
                self._unk_hv = _bipolar_hv(
                    _seed_for_token(UNK_TOKEN, salt=self.seed), self.n_dim
                )
            return self._unk_hv
        if not (0 <= idx < self.v_tok):
            raise IndexError(f"id {idx} out of range [0, {self.v_tok})")
        cached = self._codebook_cache.get(idx)
        if cached is not None:
            return cached
        token = self._id_to_token[idx]
        hv = _bipolar_hv(_seed_for_token(token, salt=self.seed), self.n_dim)
        self._codebook_cache[idx] = hv
        return hv

    def encode(self, token: str) -> tuple[int, np.ndarray]:
        """Convenience: (id, HV). OOV tokens map to (unk_id, UNK_HV)."""
        idx = self.token_to_id(token)
        return idx, self.id_to_codebook_vec(idx)

    def codebook_matrix(self) -> np.ndarray:
        """Return [V_TOK + 1, n_dim] full codebook (UNK in last row); caches all entries."""
        rows = [self.id_to_codebook_vec(i) for i in range(self.v_tok)]
        rows.append(self.id_to_codebook_vec(self.unk_id))
        return np.stack(rows, axis=0).astype(np.float32)

    # ---- bulk build ----
    def build_from_corpus(self, tokens: Iterable[str], v_top: int) -> None:
        """Build vocab from top-`v_top` most-frequent tokens in `tokens` stream.

        Order: by descending frequency, ties broken by first-seen order
        (deterministic). Raises if called on a non-empty vocab.
        """
        if self.v_tok > 0:
            raise RuntimeError(
                "build_from_corpus requires empty vocab; "
                "use add_token() to grow an existing vocab."
            )
        if v_top <= 0:
            raise ValueError(f"v_top must be > 0; got {v_top}")
        counts: dict[str, int] = {}
        first_seen: dict[str, int] = {}
        for i, t in enumerate(tokens):
            counts[t] = counts.get(t, 0) + 1
            if t not in first_seen:
                first_seen[t] = i
        sorted_tokens = sorted(
            counts.items(), key=lambda kv: (-kv[1], first_seen[kv[0]])
        )
        for token, freq in sorted_tokens[: min(v_top, self.v_max)]:
            self.add_token(token, frequency=freq)

    def grow_with(self, new_tokens: list[str]) -> int:
        """Add tokens not already in vocab; returns # added. Frozen vocab raises."""
        if self._frozen:
            raise RuntimeError("vocab is frozen; cannot grow.")
        added = 0
        for t in new_tokens:
            if t not in self._token_to_id:
                self.add_token(t, frequency=0)
                added += 1
        return added

    def freeze(self) -> None:
        """Disable further vocabulary growth. Required before chain-grade reporting."""
        self._frozen = True

    # ---- persistence ----
    def save(self, path: str | Path) -> None:
        """Persist vocab (one JSON line per token + a final header line) to `path`.

        Format: first line = header dict {n_dim, v_max, seed, v_tok, frozen,
        provenance}; subsequent lines = one per token in id order
        {id, token, frequency, codebook_seed}. UNK is implicit (last slot;
        seed = blake2b(UNK_TOKEN, salt=seed)).

        The codebook MATRIX itself is NOT serialized (it is deterministic
        from token + seed); load() regenerates lazily on first id_to_codebook_vec.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            header = {
                "__header__": True,
                "n_dim": self.n_dim,
                "v_max": self.v_max,
                "seed": self.seed,
                "v_tok": self.v_tok,
                "frozen": self._frozen,
                "provenance": self._provenance,
            }
            f.write(json.dumps(header) + "\n")
            for idx, token in enumerate(self._id_to_token):
                row = {
                    "id": idx,
                    "token": token,
                    "frequency": self._frequency[idx],
                    "codebook_seed": _seed_for_token(token, salt=self.seed),
                }
                f.write(json.dumps(row) + "\n")

    @classmethod
    def load(cls, path: str | Path) -> "TokenVocab":
        """Inverse of save(). Restores vocab state; codebook regenerates lazily."""
        path = Path(path)
        with path.open("r", encoding="utf-8") as f:
            lines = [ln for ln in f if ln.strip()]
        if not lines:
            raise ValueError(f"empty vocab file {path}")
        header = json.loads(lines[0])
        if not header.get("__header__"):
            raise ValueError(f"missing header line in {path}")
        vocab = cls(
            n_dim=int(header["n_dim"]),
            v_max=int(header["v_max"]),
            seed=int(header.get("seed", 0)),
        )
        for ln in lines[1:]:
            row = json.loads(ln)
            vocab.add_token(row["token"], frequency=int(row.get("frequency", 1)))
        if bool(header.get("frozen", False)):
            vocab.freeze()
        return vocab

    def __repr__(self) -> str:
        return (
            f"TokenVocab(n_dim={self.n_dim}, v_tok={self.v_tok}, "
            f"v_max={self.v_max}, frozen={self._frozen}, "
            f"provenance={self._provenance})"
        )
