"""One-time script generator for Q-A3 ladder scripts."""
import os

def make_mmid(L, full_mode=True):
    if full_mode:
        lead = [50, 25, 12, 6, 3]
    else:
        lead = [10, 5, 3]
    n_remaining = L - 2 - len(lead)
    return lead + [2] * n_remaining

def format_mmid_rows(mmid, cols=20):
    rows = []
    for i in range(0, len(mmid), cols):
        chunk = mmid[i:i+cols]
        rows.append("        " + ", ".join(str(x) for x in chunk) + ",")
    return "\n".join(rows)

def gen_n16384_script(L):
    N = 16384
    anchor = f"q_a3_l{L}_cross_layer_composition_v1_n{N}"
    rung = 81 + (L - 100)
    mmid_full = make_mmid(L, True)
    mmid_smoke = make_mmid(L, False)
    assert len(mmid_full) == L - 2
    assert len(mmid_smoke) == L - 2
    mmid_full_str = format_mmid_rows(mmid_full)
    mmid_smoke_str = format_mmid_rows(mmid_smoke)
    alpha_val = 100/N
    script = (
        f'"""\n'
        f'{anchor} -- Q-A3/PP-12: L={L} cross-layer composition at N={N}.\n\n'
        f'CONTEXT (v376 cycle 46 all-night burst):\n'
        f'  N={N} series: L=20..L=100 all EXACT-1.0000 (cycles 42-45, CENTURY RUNG passed).\n'
        f'  L={L} is rung {rung} in the N={N} depth ladder.\n'
        f'  ECC criterion: depth UNLIMITED when per-stage max(alpha_k) < alpha_c=0.138.\n'
        f'  Per-stage alpha = 100/{N} = {alpha_val:.4f} << alpha_c. Theory predicts continued EXACT fidelity.\n\n'
        f'SCIENTIFIC QUESTION:\n'
        f'  Does cross-layer composition fidelity remain EXACT-1.0 at L={L} N={N}?\n\n'
        f'PRE-REGISTERED BANDS (PP-12/Q-A3 ladder continuation):\n'
        f'  HARD-PASS: all {L} level fidelities >= 0.9999 unanimous (5/5 seeds) AND l{L}_acc >= 0.5.\n'
        f'  MIDDLE: any L_fid in [0.85, 0.9999) OR graceful degradation.\n'
        f'  HARD-FAIL: any L_fid < 0.85 OR l{L}_acc < 0.5.\n\n'
        f'FORMULA SELF-TESTS (PROT-022):\n'
        f'  1. L={L} chain: {L-1}-ctx Hadamard roundtrip recovers xi_L1.\n'
        f'     [INPUT: 2-element +-1 vectors, {L-1} context ops] [EXPECTED: decode = xi_L1 exactly]\n'
        f'  2. All alphas < alpha_c=0.138 at N={N}. M_INNER=100 -> alpha={alpha_val:.4f} < 0.138.\n'
        f'     [INPUT: M_INNER=100, N={N}] [EXPECTED: alpha={alpha_val:.4f} < 0.138]\n'
        f'  3. GPU memory > 0 after W build.\n'
        f'  4. M_MID length == L_DEPTH - 2 == {L-2}.\n'
        f'     [INPUT: L_DEPTH={L}] [EXPECTED: len(M_MID)={L-2}]\n\n'
        f'PROT-018: anchor has _n{N}; N MUST = {N}.\n'
        f'PROT-021: seed checkpoints keyed with run_mode + L.\n'
        f'QUEUE: overnight_queue (GPU; on-demand W build).\n'
        f'TIMEOUT ESTIMATE: ~45s extrapolated from L=94-100. Use PROT-019 floor: 21600s.\n'
        f'"""\n'
        f'import sys\n'
        f'sys.stdout.reconfigure(encoding=\'utf-8\', errors=\'replace\')\n'
        f'sys.stderr.reconfigure(encoding=\'utf-8\', errors=\'replace\')\n\n'
        f'import os\n'
        f'import argparse\n'
        f'import time\n'
        f'import json\n'
        f'from pathlib import Path\n'
        f'from typing import Dict, List\n\n'
        f'REPO = Path(__file__).resolve().parent.parent\n'
        f'sys.path.insert(0, str(REPO))\n\n'
        f'try:\n'
        f'    import torch\n'
        f'    import torch.cuda\n'
        f'except ImportError:\n'
        f'    print("[FATAL] torch not installed.", flush=True)\n'
        f'    sys.exit(1)\n\n'
        f'if not torch.cuda.is_available():\n'
        f'    print("[FATAL] CUDA not available. This script requires a GPU.", flush=True)\n'
        f'    sys.exit(1)\n\n'
        f'DEVICE = torch.device(\'cuda\')\n'
        f'print(f"[GPU] device={{DEVICE}} name={{torch.cuda.get_device_name(0)}} "\n'
        f'      f"total_mem={{torch.cuda.get_device_properties(0).total_memory / 1e9:.1f}}GB", flush=True)\n\n'
        f'from experiments._seed_checkpoint import get_output_dir, resumable_seeds, write_partial, aggregate_partials\n\n'
        f'ANCHOR_NAME = "{anchor}"\n\n'
        f'_N_SUFFIX = {N}\n'
        f'N = {N}\n'
        f'assert N == _N_SUFFIX, f"PROT-018: anchor _n{{_N_SUFFIX}} but N={{N}}"\n\n'
        f'RUN_MODE = ("smoke" if "--smoke" in sys.argv else os.environ.get("HDLAB_RUN_MODE", "full")).lower()\n\n'
        f'_ap = argparse.ArgumentParser()\n'
        f'_ap.add_argument("--smoke", action="store_true")\n'
        f'_ap.add_argument("--self-test", action="store_true")\n'
        f'_ARGS, _ = _ap.parse_known_args()\n\n'
        f'ALPHA_C = 0.138\n'
        f'L_DEPTH = {L}\n'
        f'HP_FIDELITY_UNANI_THRESH = 0.9999\n'
        f'MIDDLE_FIDELITY = 0.85\n'
        f'HF_FIDELITY = 0.85\n'
        f'HP_LACC = 0.5\n'
        f'HF_LACC = 0.5\n'
        f'NOISE_FRAC = 0.10\n\n'
        f'_W_ONDEMAND_GB = {N} * {N} * 4 / 1e9\n'
        f'assert _W_ONDEMAND_GB < 1.2, f"W on-demand size: {{_W_ONDEMAND_GB:.3f}} GB"\n\n'
        f'if RUN_MODE == "smoke":\n'
        f'    N_ACTIVE = 512\n'
        f'    SEEDS = [7, 17]\n'
        f'    M_INNER = 20\n'
        f'    M_MID = [\n'
        f'{mmid_smoke_str}\n'
        f'    ]\n'
        f'    M_OUTER = 2\n'
        f'    N_QUERIES = 2\n'
        f'else:\n'
        f'    N_ACTIVE = N\n'
        f'    SEEDS = [7, 17, 23, 31, 41]\n'
        f'    M_INNER = 100\n'
        f'    M_MID = [\n'
        f'{mmid_full_str}\n'
        f'    ]\n'
        f'    M_OUTER = 2\n'
        f'    N_QUERIES = 2\n\n'
        f'assert len(M_MID) == L_DEPTH - 2, f"M_MID length {{len(M_MID)}} expected {{L_DEPTH - 2}}"\n\n\n'
        f'def _selftest_lN_chain():\n'
        f'    n_ctx = L_DEPTH - 1\n'
        f'    base = [[1.0, -1.0], [-1.0, 1.0], [1.0, 1.0], [-1.0, -1.0]]\n'
        f'    ctxs = [torch.tensor(base[i % 4], dtype=torch.float32, device=DEVICE) for i in range(n_ctx)]\n'
        f'    xi_L1 = torch.tensor([1.0, -1.0], dtype=torch.float32, device=DEVICE)\n'
        f'    xi = xi_L1.clone()\n'
        f'    for c in ctxs:\n'
        f'        xi = c * xi\n'
        f'    xi_dec = xi.clone()\n'
        f'    for c in reversed(ctxs):\n'
        f'        xi_dec = xi_dec * c\n'
        f'    assert torch.allclose(xi_dec, xi_L1, atol=1e-6), f"L{{L_DEPTH}} chain decode failed: {{xi_dec}}"\n\n\n'
        f'def _instrumentation_selftest():\n'
        f'    _selftest_lN_chain()\n'
        f'    n_dim = N_ACTIVE\n'
        f'    ms = [M_INNER] + M_MID + [M_OUTER]\n'
        f'    assert len(ms) == L_DEPTH, f"M schedule length {{len(ms)}} != L_DEPTH {{L_DEPTH}}"\n'
        f'    for i, m in enumerate(ms, 1):\n'
        f'        al = m / n_dim\n'
        f'        assert al < ALPHA_C, f"L{{i}} alpha {{al:.4f}} >= alpha_c={{ALPHA_C}}"\n'
        f'    dummy = torch.zeros((512, 512), device=DEVICE, dtype=torch.float32)\n'
        f'    mem = torch.cuda.memory_allocated(0)\n'
        f'    assert mem > 0, f"GPU memory not allocated: {{mem}}"\n'
        f'    del dummy\n'
        f'    print(f"[selftest] PASS: L{{L_DEPTH}} chain decode ok, capacity_ok, gpu_mem_ok N={{n_dim}}", flush=True)\n\n\n'
        f'_instrumentation_selftest()\n'
        f'if _ARGS.self_test:\n'
        f'    sys.exit(0)\n\n\n'
        f'def hopfield_retrieve_gpu(W: torch.Tensor, probe: torch.Tensor, n_steps: int = 5) -> torch.Tensor:\n'
        f'    state = probe.clone()\n'
        f'    for _ in range(n_steps):\n'
        f'        h = W @ state\n'
        f'        state = torch.sign(h)\n'
        f'        state[state == 0] = 1.0\n'
        f'    return state\n\n\n'
        f'def cosine_sim_gpu(a: torch.Tensor, b: torch.Tensor) -> float:\n'
        f'    na = float(a.norm())\n'
        f'    nb = float(b.norm())\n'
        f'    if na < 1e-12 or nb < 1e-12:\n'
        f'        return 0.0\n'
        f'    return float(torch.dot(a, b)) / (na * nb)\n\n\n'
        f'def run_seed(seed: int, n_dim: int) -> Dict:\n'
        f'    gen = torch.Generator(device=DEVICE)\n'
        f'    gen.manual_seed(seed)\n'
        f'    t0 = time.time()\n\n'
        f'    def bsc(m, n_d):\n'
        f'        return (torch.randint(0, 2, (m, n_d), generator=gen, device=DEVICE).float() * 2 - 1)\n\n'
        f'    Xi_inner = bsc(M_INNER, n_dim)\n'
        f'    Xi_layers = [Xi_inner]\n'
        f'    Xi_ctxs = []\n'
        f'    curr = Xi_inner\n'
        f'    for i, m in enumerate(M_MID):\n'
        f'        ctx = bsc(m, n_dim)\n'
        f'        Xi_ctxs.append(ctx)\n'
        f'        mid = ctx * curr[:m]\n'
        f'        Xi_layers.append(mid)\n'
        f'        curr = mid\n'
        f'    ctx_outer = bsc(M_OUTER, n_dim)\n'
        f'    Xi_ctxs.append(ctx_outer)\n'
        f'    Xi_outer = ctx_outer * curr[:M_OUTER]\n'
        f'    Xi_layers.append(Xi_outer)\n\n'
        f'    assert len(Xi_layers) == L_DEPTH, f"Xi_layers count {{len(Xi_layers)}} != {{L_DEPTH}}"\n\n'
        f'    xi_mem_gb = torch.cuda.memory_allocated(0) / 1e9\n'
        f'    print(f"  [seed={{seed}} N={{n_dim}}] GPU memory after Xi build: {{xi_mem_gb:.3f}} GB", flush=True)\n\n'
        f'    level_fids = {{f"L{{l}}": [] for l in range(1, L_DEPTH + 1)}}\n'
        f'    l_acc = []\n\n'
        f'    for q_idx in range(min(N_QUERIES, M_OUTER)):\n'
        f'        xi_outer_true = Xi_outer[q_idx]\n'
        f'        probe = xi_outer_true.clone()\n'
        f'        flip_mask = (torch.rand(n_dim, generator=gen, device=DEVICE) < NOISE_FRAC)\n'
        f'        probe[flip_mask] *= -1.0\n\n'
        f'        decoded = [None] * L_DEPTH\n\n'
        f'        W_top = (Xi_layers[L_DEPTH - 1].t() @ Xi_layers[L_DEPTH - 1]) / n_dim\n'
        f'        ret = hopfield_retrieve_gpu(W_top, probe)\n'
        f'        del W_top\n'
        f'        decoded[L_DEPTH - 1] = ret\n'
        f'        level_fids[f"L{{L_DEPTH}}"].append(cosine_sim_gpu(ret, xi_outer_true))\n\n'
        f'        for l_idx in range(L_DEPTH - 2, -1, -1):\n'
        f'            l_label = l_idx + 1\n'
        f'            ptr = decoded[l_idx + 1] * Xi_ctxs[l_idx][q_idx]\n'
        f'            W_l = (Xi_layers[l_idx].t() @ Xi_layers[l_idx]) / n_dim\n'
        f'            ret_l = hopfield_retrieve_gpu(W_l, ptr)\n'
        f'            del W_l\n'
        f'            decoded[l_idx] = ret_l\n'
        f'            fid = cosine_sim_gpu(ret_l, Xi_layers[l_idx][q_idx])\n'
        f'            level_fids[f"L{{l_label}}"].append(fid)\n\n'
        f'        l_acc.append(cosine_sim_gpu(decoded[0], Xi_layers[0][q_idx]))\n\n'
        f'    mean_fids = {{k: float(sum(v) / len(v)) if v else 0.0 for k, v in level_fids.items()}}\n'
        f'    mean_lacc = float(sum(l_acc) / len(l_acc)) if l_acc else 0.0\n\n'
        f'    peak_mem = torch.cuda.max_memory_allocated(0) / 1e9\n'
        f'    elapsed = time.time() - t0\n'
        f'    print(f"  [seed={{seed}}] l{{L_DEPTH}}_acc={{mean_lacc:.4f}} peak_gpu={{peak_mem:.3f}}GB "\n'
        f'          f"elapsed={{elapsed:.2f}}s", flush=True)\n\n'
        f'    result = {{\n'
        f'        "seed": seed, "N": n_dim, "run_mode": RUN_MODE,\n'
        f'        f"l{{L_DEPTH}}_accuracy": float(mean_lacc),\n'
        f'        "peak_gpu_gb": float(peak_mem), "elapsed_s": elapsed,\n'
        f'    }}\n'
        f'    for k, v in mean_fids.items():\n'
        f'        result[f"fid_{{k.lower()}}"] = v\n'
        f'    return result\n\n\n'
        f'def compute_verdict(results: List[Dict]) -> tuple:\n'
        f'    if not results:\n'
        f'        return ("HARD_FAIL", "No valid results.")\n\n'
        f'    def mean_key(k):\n'
        f'        vs = [r[k] for r in results if k in r]\n'
        f'        return float(sum(vs) / len(vs)) if vs else 0.0\n\n'
        f'    fid_vals = {{f"L{{l}}": mean_key(f"fid_l{{l}}") for l in range(1, L_DEPTH + 1)}}\n'
        f'    lacc = mean_key(f"l{{L_DEPTH}}_accuracy")\n\n'
        f'    fid_list = [fid_vals[f"L{{l}}"] for l in range(1, L_DEPTH + 1)]\n'
        f'    summary = (" ".join(f"L{{l}}:{{fid_vals[f\'L{{l}}\']:.4f}}" for l in range(max(1, L_DEPTH-4), L_DEPTH + 1)) +\n'
        f'               f" l{{L_DEPTH}}_acc={{lacc:.4f}} n_seeds={{len(results)}}")\n\n'
        f'    if any(f < HF_FIDELITY for f in fid_list) or lacc < HF_LACC:\n'
        f'        return ("HARD_FAIL", f"HARD_FAIL: any fid<{{HF_FIDELITY}} or l{{L_DEPTH}}_acc<{{HF_LACC}}. {{summary}}")\n\n'
        f'    all_unanimous = all(f >= HP_FIDELITY_UNANI_THRESH for f in fid_list)\n'
        f'    if all_unanimous and lacc >= HP_LACC:\n'
        f'        return ("HARD_PASS", f"HARD_PASS: all {{L_DEPTH}} levels EXACT-1.0 unanimous "\n'
        f'                f"+ l{{L_DEPTH}}_acc HP at N={{N}}. {{summary}}")\n\n'
        f'    if any(f < MIDDLE_FIDELITY for f in fid_list):\n'
        f'        return ("MIDDLE_BAND", f"MIDDLE_BAND: graceful degradation (some fid<{{MIDDLE_FIDELITY}}). {{summary}}")\n\n'
        f'    return ("MIDDLE_BAND", f"MIDDLE_BAND: some fids in [{{MIDDLE_FIDELITY}},1.0). {{summary}}")\n\n\n'
        f'def _prot018_startup_check(n_actual: int) -> None:\n'
        f'    if RUN_MODE == "smoke":\n'
        f'        return\n'
        f'    if n_actual != _N_SUFFIX:\n'
        f'        raise RuntimeError(\n'
        f'            f"PROT-018 VIOLATION: anchor \'{{ANCHOR_NAME}}\' binds N={{_N_SUFFIX}} "\n'
        f'            f"but running at N={{n_actual}}.")\n\n\n'
        f'print(f"[config] PROT-018 N={{N}} n_active={{N_ACTIVE}} mode={{RUN_MODE}} L={{L_DEPTH}}", flush=True)\n'
        f'_prot018_startup_check(N_ACTIVE if RUN_MODE == "smoke" else N)\n\n'
        f'out_dir = get_output_dir(ANCHOR_NAME)\n'
        f'run_config = {{"N": N, "L": L_DEPTH, "run_mode": RUN_MODE}}\n'
        f'done, remaining = resumable_seeds(SEEDS, out_dir, run_config=run_config)\n'
        f'print(f"[ckpt] {{len(done)}} seeds done, {{len(remaining)}} to run", flush=True)\n\n'
        f't_sweep_start = time.time()\n'
        f'for seed in remaining:\n'
        f'    print(f"[seed={{seed}}] {{ANCHOR_NAME}}...", flush=True)\n'
        f'    result = run_seed(seed, N_ACTIVE if RUN_MODE == "smoke" else N)\n'
        f'    write_partial(out_dir, seed, result)\n\n'
        f'per_seed = aggregate_partials(out_dir, SEEDS)\n'
        f'all_results = list(per_seed.values())\n'
        f'verdict, verdict_msg = compute_verdict(all_results)\n\n'
        f'print(f"\\n[VERDICT] {{verdict}}: {{verdict_msg}}", flush=True)\n\n'
        f'elapsed_total = time.time() - t_sweep_start\n'
        f'peak_mem_gb = torch.cuda.max_memory_allocated(0) / 1e9\n'
        f'print(f"[GPU] peak memory allocated: {{peak_mem_gb:.3f}} GB", flush=True)\n'
        f'assert peak_mem_gb > 0.01, f"GPU util check FAIL: peak_gpu={{peak_mem_gb:.3f}}GB (< 100MB)"\n\n'
        f'metrics = {{\n'
        f'    "anchor_name": ANCHOR_NAME,\n'
        f'    "verdict": verdict, "verdict_msg": verdict_msg,\n'
        f'    "N": N, "L": L_DEPTH, "run_mode": RUN_MODE,\n'
        f'    "n_seeds": len(SEEDS), "elapsed_s": elapsed_total,\n'
        f'    "summary": verdict_msg,\n'
        f'    "per_seed": [\n'
        f'        {{"seed": r.get("seed"),\n'
        f'         "lacc": r.get(f"l{{L_DEPTH}}_accuracy"),\n'
        f'         "peak_gpu_gb": r.get("peak_gpu_gb"),\n'
        f'         "elapsed_s": r.get("elapsed_s")}}\n'
        f'        for r in all_results\n'
        f'    ],\n'
        f'}}\n'
        f'metrics_path = out_dir / "metrics.json"\n'
        f'metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")\n'
        f'print(f"[metrics] written to {{metrics_path}}", flush=True)\n'
    )
    return anchor, script


def gen_n8192_script(L):
    N = 8192
    anchor = f"q_a3_l{L}_cross_layer_composition_v1_n{N}"
    rung = 43 + (L - 62)
    mmid_full = make_mmid(L, True)
    mmid_smoke = make_mmid(L, False)
    assert len(mmid_full) == L - 2
    assert len(mmid_smoke) == L - 2
    mmid_full_str = format_mmid_rows(mmid_full)
    mmid_smoke_str = format_mmid_rows(mmid_smoke)
    alpha_val = 100/N
    mem_mb = N*N*4/1e6
    script = (
        f'"""\n'
        f'{anchor} -- Q-A3/PP-12: L={L} cross-layer composition at N={N}.\n\n'
        f'CONTEXT (v376 cycle 46 all-night burst):\n'
        f'  N={N} series: L=19..L=62 all EXACT-1.0000 (cycles 42-45).\n'
        f'  L={L} is rung {rung} in the N={N} depth ladder.\n'
        f'  ECC criterion: depth UNLIMITED when per-stage max(alpha_k) < alpha_c=0.138.\n'
        f'  Per-stage alpha = 100/{N} = {alpha_val:.4f} << alpha_c=0.138. Theory predicts EXACT fidelity.\n\n'
        f'SCIENTIFIC QUESTION:\n'
        f'  Does cross-layer composition fidelity remain EXACT-1.0 at L={L} N={N}?\n\n'
        f'MEMORY ESTIMATE (on-demand W):\n'
        f'  One W matrix at a time: {N} x {N} x 4 bytes = {mem_mb:.0f} MB. Well within 8 GB GPU.\n\n'
        f'PRE-REGISTERED BANDS (Q-A3 N={N} ladder continuation):\n'
        f'  HARD-PASS: all {L} level fidelities >= 0.9999 unanimous (5/5 seeds) AND l{L}_acc >= 0.5.\n'
        f'  MIDDLE: any L_fid in [0.85, 0.9999) OR graceful degradation.\n'
        f'  HARD-FAIL: any L_fid < 0.85 OR l{L}_acc < 0.5.\n\n'
        f'FORMULA SELF-TESTS (PROT-022):\n'
        f'  1. L={L} chain: {L-1}-ctx Hadamard roundtrip recovers xi_L1.\n'
        f'     [INPUT: 2-element +-1 vectors, {L-1} context ops] [EXPECTED: decode = xi_L1 exactly]\n'
        f'  2. All alphas < alpha_c=0.138 at N={N}. M_INNER=100 -> alpha={alpha_val:.4f} < 0.138.\n'
        f'  3. GPU memory > 0 after W build.\n'
        f'  4. Memory on-demand per W: {N}*{N}*4 = {mem_mb:.0f} MB < 1 GB.\n\n'
        f'PROT-018: anchor has _n{N}; N MUST = {N}.\n'
        f'PROT-021: seed checkpoints keyed with run_mode + L.\n'
        f'QUEUE: overnight_queue (GPU; on-demand W build at N={N}).\n'
        f'TIMEOUT ESTIMATE: L=58-62 N={N} elapsed ~5-8s (5-seed). Use PROT-019 floor: 21600s.\n'
        f'"""\n'
        f'import sys\n'
        f'sys.stdout.reconfigure(encoding=\'utf-8\', errors=\'replace\')\n'
        f'sys.stderr.reconfigure(encoding=\'utf-8\', errors=\'replace\')\n\n'
        f'import os\n'
        f'import argparse\n'
        f'import time\n'
        f'import json\n'
        f'from pathlib import Path\n'
        f'from typing import Dict, List\n\n'
        f'REPO = Path(__file__).resolve().parent.parent\n'
        f'sys.path.insert(0, str(REPO))\n\n'
        f'try:\n'
        f'    import torch\n'
        f'    import torch.cuda\n'
        f'except ImportError:\n'
        f'    print("[FATAL] torch not installed.", flush=True)\n'
        f'    sys.exit(1)\n\n'
        f'if not torch.cuda.is_available():\n'
        f'    print("[FATAL] CUDA not available. This script requires a GPU.", flush=True)\n'
        f'    sys.exit(1)\n\n'
        f'DEVICE = torch.device(\'cuda\')\n'
        f'print(f"[GPU] device={{DEVICE}} name={{torch.cuda.get_device_name(0)}} "\n'
        f'      f"total_mem={{torch.cuda.get_device_properties(0).total_memory / 1e9:.1f}}GB", flush=True)\n\n'
        f'from experiments._seed_checkpoint import get_output_dir, resumable_seeds, write_partial, aggregate_partials\n\n'
        f'ANCHOR_NAME = "{anchor}"\n\n'
        f'_N_SUFFIX = {N}\n'
        f'N = {N}\n'
        f'assert N == _N_SUFFIX, f"PROT-018: anchor _n{{_N_SUFFIX}} but N={{N}}"\n\n'
        f'RUN_MODE = ("smoke" if "--smoke" in sys.argv else os.environ.get("HDLAB_RUN_MODE", "full")).lower()\n\n'
        f'_ap = argparse.ArgumentParser()\n'
        f'_ap.add_argument("--smoke", action="store_true")\n'
        f'_ap.add_argument("--self-test", action="store_true")\n'
        f'_ARGS, _ = _ap.parse_known_args()\n\n'
        f'ALPHA_C = 0.138\n'
        f'L_DEPTH = {L}\n'
        f'HP_FIDELITY_UNANI_THRESH = 0.9999\n'
        f'MIDDLE_FIDELITY = 0.85\n'
        f'HF_FIDELITY = 0.85\n'
        f'HP_LACC = 0.5\n'
        f'HF_LACC = 0.5\n'
        f'NOISE_FRAC = 0.10\n\n'
        f'_W_ONDEMAND_GB = {N} * {N} * 4 / 1e9\n'
        f'assert _W_ONDEMAND_GB < 1.0, f"W on-demand size: {{_W_ONDEMAND_GB:.3f}} GB"\n\n'
        f'if RUN_MODE == "smoke":\n'
        f'    N_ACTIVE = 512\n'
        f'    SEEDS = [7, 17]\n'
        f'    M_INNER = 20\n'
        f'    M_MID = [\n'
        f'{mmid_smoke_str}\n'
        f'    ]\n'
        f'    M_OUTER = 2\n'
        f'    N_QUERIES = 2\n'
        f'else:\n'
        f'    N_ACTIVE = N\n'
        f'    SEEDS = [7, 17, 23, 31, 41]\n'
        f'    M_INNER = 100\n'
        f'    M_MID = [\n'
        f'{mmid_full_str}\n'
        f'    ]\n'
        f'    M_OUTER = 2\n'
        f'    N_QUERIES = 2\n\n'
        f'assert len(M_MID) == L_DEPTH - 2, f"M_MID length {{len(M_MID)}} expected {{L_DEPTH - 2}}"\n\n\n'
        f'def _selftest_lN_chain():\n'
        f'    n_ctx = L_DEPTH - 1\n'
        f'    base = [[1.0, -1.0], [-1.0, 1.0], [1.0, 1.0], [-1.0, -1.0]]\n'
        f'    ctxs = [torch.tensor(base[i % 4], dtype=torch.float32, device=DEVICE) for i in range(n_ctx)]\n'
        f'    xi_L1 = torch.tensor([1.0, -1.0], dtype=torch.float32, device=DEVICE)\n'
        f'    xi = xi_L1.clone()\n'
        f'    for c in ctxs:\n'
        f'        xi = c * xi\n'
        f'    xi_dec = xi.clone()\n'
        f'    for c in reversed(ctxs):\n'
        f'        xi_dec = xi_dec * c\n'
        f'    assert torch.allclose(xi_dec, xi_L1, atol=1e-6), f"L{{L_DEPTH}} chain decode failed: {{xi_dec}}"\n\n\n'
        f'def _instrumentation_selftest():\n'
        f'    _selftest_lN_chain()\n'
        f'    n_dim = N_ACTIVE\n'
        f'    ms = [M_INNER] + M_MID + [M_OUTER]\n'
        f'    assert len(ms) == L_DEPTH, f"M schedule length {{len(ms)}} != L_DEPTH {{L_DEPTH}}"\n'
        f'    for i, m in enumerate(ms, 1):\n'
        f'        al = m / n_dim\n'
        f'        assert al < ALPHA_C, f"L{{i}} alpha {{al:.4f}} >= alpha_c={{ALPHA_C}}"\n'
        f'    dummy = torch.zeros((512, 512), device=DEVICE, dtype=torch.float32)\n'
        f'    mem = torch.cuda.memory_allocated(0)\n'
        f'    assert mem > 0, f"GPU memory not allocated: {{mem}}"\n'
        f'    del dummy\n'
        f'    print(f"[selftest] PASS: L{{L_DEPTH}} chain decode ok, capacity_ok, gpu_mem_ok N={{n_dim}}", flush=True)\n\n\n'
        f'_instrumentation_selftest()\n'
        f'if _ARGS.self_test:\n'
        f'    sys.exit(0)\n\n\n'
        f'def hopfield_retrieve_gpu(W: torch.Tensor, probe: torch.Tensor, n_steps: int = 5) -> torch.Tensor:\n'
        f'    state = probe.clone()\n'
        f'    for _ in range(n_steps):\n'
        f'        h = W @ state\n'
        f'        state = torch.sign(h)\n'
        f'        state[state == 0] = 1.0\n'
        f'    return state\n\n\n'
        f'def cosine_sim_gpu(a: torch.Tensor, b: torch.Tensor) -> float:\n'
        f'    na = float(a.norm())\n'
        f'    nb = float(b.norm())\n'
        f'    if na < 1e-12 or nb < 1e-12:\n'
        f'        return 0.0\n'
        f'    return float(torch.dot(a, b)) / (na * nb)\n\n\n'
        f'def run_seed(seed: int, n_dim: int) -> Dict:\n'
        f'    gen = torch.Generator(device=DEVICE)\n'
        f'    gen.manual_seed(seed)\n'
        f'    t0 = time.time()\n\n'
        f'    def bsc(m, n_d):\n'
        f'        return (torch.randint(0, 2, (m, n_d), generator=gen, device=DEVICE).float() * 2 - 1)\n\n'
        f'    Xi_inner = bsc(M_INNER, n_dim)\n'
        f'    Xi_layers = [Xi_inner]\n'
        f'    Xi_ctxs = []\n'
        f'    curr = Xi_inner\n'
        f'    for i, m in enumerate(M_MID):\n'
        f'        ctx = bsc(m, n_dim)\n'
        f'        Xi_ctxs.append(ctx)\n'
        f'        mid = ctx * curr[:m]\n'
        f'        Xi_layers.append(mid)\n'
        f'        curr = mid\n'
        f'    ctx_outer = bsc(M_OUTER, n_dim)\n'
        f'    Xi_ctxs.append(ctx_outer)\n'
        f'    Xi_outer = ctx_outer * curr[:M_OUTER]\n'
        f'    Xi_layers.append(Xi_outer)\n\n'
        f'    assert len(Xi_layers) == L_DEPTH, f"Xi_layers count {{len(Xi_layers)}} != {{L_DEPTH}}"\n\n'
        f'    xi_mem_gb = torch.cuda.memory_allocated(0) / 1e9\n'
        f'    print(f"  [seed={{seed}} N={{n_dim}}] GPU memory after Xi build: {{xi_mem_gb:.3f}} GB", flush=True)\n\n'
        f'    level_fids = {{f"L{{l}}": [] for l in range(1, L_DEPTH + 1)}}\n'
        f'    l_acc = []\n\n'
        f'    for q_idx in range(min(N_QUERIES, M_OUTER)):\n'
        f'        xi_outer_true = Xi_outer[q_idx]\n'
        f'        probe = xi_outer_true.clone()\n'
        f'        flip_mask = (torch.rand(n_dim, generator=gen, device=DEVICE) < NOISE_FRAC)\n'
        f'        probe[flip_mask] *= -1.0\n\n'
        f'        decoded = [None] * L_DEPTH\n\n'
        f'        W_top = (Xi_layers[L_DEPTH - 1].t() @ Xi_layers[L_DEPTH - 1]) / n_dim\n'
        f'        ret = hopfield_retrieve_gpu(W_top, probe)\n'
        f'        del W_top\n'
        f'        decoded[L_DEPTH - 1] = ret\n'
        f'        level_fids[f"L{{L_DEPTH}}"].append(cosine_sim_gpu(ret, xi_outer_true))\n\n'
        f'        for l_idx in range(L_DEPTH - 2, -1, -1):\n'
        f'            l_label = l_idx + 1\n'
        f'            ptr = decoded[l_idx + 1] * Xi_ctxs[l_idx][q_idx]\n'
        f'            W_l = (Xi_layers[l_idx].t() @ Xi_layers[l_idx]) / n_dim\n'
        f'            ret_l = hopfield_retrieve_gpu(W_l, ptr)\n'
        f'            del W_l\n'
        f'            decoded[l_idx] = ret_l\n'
        f'            fid = cosine_sim_gpu(ret_l, Xi_layers[l_idx][q_idx])\n'
        f'            level_fids[f"L{{l_label}}"].append(fid)\n\n'
        f'        l_acc.append(cosine_sim_gpu(decoded[0], Xi_layers[0][q_idx]))\n\n'
        f'    mean_fids = {{k: float(sum(v) / len(v)) if v else 0.0 for k, v in level_fids.items()}}\n'
        f'    mean_lacc = float(sum(l_acc) / len(l_acc)) if l_acc else 0.0\n\n'
        f'    peak_mem = torch.cuda.max_memory_allocated(0) / 1e9\n'
        f'    elapsed = time.time() - t0\n'
        f'    print(f"  [seed={{seed}}] l{{L_DEPTH}}_acc={{mean_lacc:.4f}} peak_gpu={{peak_mem:.3f}}GB "\n'
        f'          f"elapsed={{elapsed:.2f}}s", flush=True)\n\n'
        f'    result = {{\n'
        f'        "seed": seed, "N": n_dim, "run_mode": RUN_MODE,\n'
        f'        f"l{{L_DEPTH}}_accuracy": float(mean_lacc),\n'
        f'        "peak_gpu_gb": float(peak_mem), "elapsed_s": elapsed,\n'
        f'    }}\n'
        f'    for k, v in mean_fids.items():\n'
        f'        result[f"fid_{{k.lower()}}"] = v\n'
        f'    return result\n\n\n'
        f'def compute_verdict(results: List[Dict]) -> tuple:\n'
        f'    if not results:\n'
        f'        return ("HARD_FAIL", "No valid results.")\n\n'
        f'    def mean_key(k):\n'
        f'        vs = [r[k] for r in results if k in r]\n'
        f'        return float(sum(vs) / len(vs)) if vs else 0.0\n\n'
        f'    fid_vals = {{f"L{{l}}": mean_key(f"fid_l{{l}}") for l in range(1, L_DEPTH + 1)}}\n'
        f'    lacc = mean_key(f"l{{L_DEPTH}}_accuracy")\n\n'
        f'    fid_list = [fid_vals[f"L{{l}}"] for l in range(1, L_DEPTH + 1)]\n'
        f'    summary = (" ".join(f"L{{l}}:{{fid_vals[f\'L{{l}}\']:.4f}}" for l in range(1, L_DEPTH + 1)) +\n'
        f'               f" l{{L_DEPTH}}_acc={{lacc:.4f}} n_seeds={{len(results)}}")\n\n'
        f'    if any(f < HF_FIDELITY for f in fid_list) or lacc < HF_LACC:\n'
        f'        return ("HARD_FAIL", f"HARD_FAIL: any fid<{{HF_FIDELITY}} or l{{L_DEPTH}}_acc<{{HF_LACC}}. {{summary}}")\n\n'
        f'    all_unanimous = all(f >= HP_FIDELITY_UNANI_THRESH for f in fid_list)\n'
        f'    if all_unanimous and lacc >= HP_LACC:\n'
        f'        return ("HARD_PASS", f"HARD_PASS: all {{L_DEPTH}} levels EXACT-1.0 unanimous "\n'
        f'                f"+ l{{L_DEPTH}}_acc HP at N={{N}}. {{summary}}")\n\n'
        f'    if any(f < MIDDLE_FIDELITY for f in fid_list):\n'
        f'        return ("MIDDLE_BAND", f"MIDDLE_BAND: graceful degradation (some fid<{{MIDDLE_FIDELITY}}). {{summary}}")\n\n'
        f'    return ("MIDDLE_BAND", f"MIDDLE_BAND: some fids in [{{MIDDLE_FIDELITY}},1.0). {{summary}}")\n\n\n'
        f'def _prot018_startup_check(n_actual: int) -> None:\n'
        f'    if RUN_MODE == "smoke":\n'
        f'        return\n'
        f'    if n_actual != _N_SUFFIX:\n'
        f'        raise RuntimeError(\n'
        f'            f"PROT-018 VIOLATION: anchor \'{{ANCHOR_NAME}}\' binds N={{_N_SUFFIX}} "\n'
        f'            f"but running at N={{n_actual}}.")\n\n\n'
        f'print(f"[config] PROT-018 N={{N}} n_active={{N_ACTIVE}} mode={{RUN_MODE}} L={{L_DEPTH}}", flush=True)\n'
        f'_prot018_startup_check(N_ACTIVE if RUN_MODE == "smoke" else N)\n\n'
        f'out_dir = get_output_dir(ANCHOR_NAME)\n'
        f'run_config = {{"N": N, "L": L_DEPTH, "run_mode": RUN_MODE}}\n'
        f'done, remaining = resumable_seeds(SEEDS, out_dir, run_config=run_config)\n'
        f'print(f"[ckpt] {{len(done)}} seeds done, {{len(remaining)}} to run", flush=True)\n\n'
        f't_sweep_start = time.time()\n'
        f'for seed in remaining:\n'
        f'    print(f"[seed={{seed}}] {{ANCHOR_NAME}}...", flush=True)\n'
        f'    result = run_seed(seed, N_ACTIVE if RUN_MODE == "smoke" else N)\n'
        f'    write_partial(out_dir, seed, result)\n\n'
        f'per_seed = aggregate_partials(out_dir, SEEDS)\n'
        f'all_results = list(per_seed.values())\n'
        f'verdict, verdict_msg = compute_verdict(all_results)\n\n'
        f'print(f"\\n[VERDICT] {{verdict}}: {{verdict_msg}}", flush=True)\n\n'
        f'elapsed_total = time.time() - t_sweep_start\n'
        f'peak_mem_gb = torch.cuda.max_memory_allocated(0) / 1e9\n'
        f'print(f"[GPU] peak memory allocated: {{peak_mem_gb:.3f}} GB", flush=True)\n'
        f'assert peak_mem_gb > 0.01, f"GPU util check FAIL: peak_gpu={{peak_mem_gb:.3f}}GB (< 100MB)"\n\n'
        f'metrics = {{\n'
        f'    "anchor_name": ANCHOR_NAME,\n'
        f'    "verdict": verdict, "verdict_msg": verdict_msg,\n'
        f'    "N": N, "L": L_DEPTH, "run_mode": RUN_MODE,\n'
        f'    "n_seeds": len(SEEDS), "elapsed_s": elapsed_total,\n'
        f'    "per_seed": [\n'
        f'        {{"seed": r.get("seed"),\n'
        f'         "lacc": r.get(f"l{{L_DEPTH}}_accuracy"),\n'
        f'         "peak_gpu_gb": r.get("peak_gpu_gb"),\n'
        f'         "elapsed_s": r.get("elapsed_s")}}\n'
        f'        for r in all_results\n'
        f'    ],\n'
        f'}}\n'
        f'metrics_path = out_dir / "metrics.json"\n'
        f'metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")\n'
        f'print(f"[metrics] written to {{metrics_path}}", flush=True)\n'
    )
    return anchor, script


if __name__ == "__main__":
    base = "d:/AI/hd-instrument/experiments"
    generated = []
    for L in [101, 102, 103, 104, 105]:
        anchor, script = gen_n16384_script(L)
        path = f"{base}/exp_{anchor}.py"
        with open(path, 'w', encoding='utf-8') as f:
            f.write(script)
        generated.append(anchor)
        print(f"WRITTEN: {path}")
    for L in [63, 64, 65, 66]:
        anchor, script = gen_n8192_script(L)
        path = f"{base}/exp_{anchor}.py"
        with open(path, 'w', encoding='utf-8') as f:
            f.write(script)
        generated.append(anchor)
        print(f"WRITTEN: {path}")
    print(f"TOTAL: {len(generated)}")
    for a in generated:
        print(f"  {a}")
