"""Generate Q-A3 depth-ladder scripts for N=16384 (L=128-132) and N=8192 (L=89-93)."""
import os

EXPERIMENTS_DIR = "d:/AI/hd-instrument/experiments"


def make_n16384_script(L):
    anchor = f"q_a3_l{L}_cross_layer_composition_v1_n16384"
    smoke_tail = L - 5
    full_tail = L - 7
    smoke_mid = f"[10, 5, 3] + [2] * {smoke_tail}"
    full_mid = f"[50, 25, 12, 6, 3] + [2] * {full_tail}"
    return (
        '"""\n'
        f'{anchor} -- Q-A3/PP-12: L={L} cross-layer composition at N=16384.\n'
        '\n'
        'CONTEXT (v380 cycle 50 all-night burst):\n'
        f'  N=16384 series continues depth ladder past L=127 (HARD_PASS).\n'
        '  Per-stage alpha = 100/16384 = 0.0061 << alpha_c=0.138.\n'
        '\n'
        f'PRE-REGISTERED BANDS (Q-A3 L={L} N=16384):\n'
        f'  HARD-PASS: all {L} level fidelities >= 0.9999 unanimous (5/5 seeds) AND l{L}_acc >= 0.5.\n'
        '  MIDDLE: any L_fid in [0.85, 0.9999) OR graceful degradation.\n'
        f'  HARD-FAIL: any L_fid < 0.85 OR l{L}_acc < 0.5.\n'
        '\n'
        'PROT-018: anchor has _n16384; N MUST = 16384.\n'
        'PROT-021: seed checkpoints keyed with run_mode + L.\n'
        'QUEUE: overnight_queue (GPU). TIMEOUT: 21600s (PROT-019 floor).\n'
        '"""\n'
        'import sys\n'
        'sys.stdout.reconfigure(encoding="utf-8", errors="replace")\n'
        'sys.stderr.reconfigure(encoding="utf-8", errors="replace")\n'
        'import os, argparse, time, json\n'
        'from pathlib import Path\n'
        'from typing import Dict, List\n'
        'REPO = Path(__file__).resolve().parent.parent\n'
        'sys.path.insert(0, str(REPO))\n'
        'try:\n'
        '    import torch, torch.cuda\n'
        'except ImportError:\n'
        '    print("[FATAL] torch not installed.", flush=True); sys.exit(1)\n'
        'if not torch.cuda.is_available():\n'
        '    print("[FATAL] CUDA not available.", flush=True); sys.exit(1)\n'
        'DEVICE = torch.device("cuda")\n'
        'print(f"[GPU] device={DEVICE} total_mem={torch.cuda.get_device_properties(0).total_memory/1e9:.1f}GB", flush=True)\n'
        'from experiments._seed_checkpoint import get_output_dir, resumable_seeds, write_partial, aggregate_partials\n'
        '\n'
        f'ANCHOR_NAME = "{anchor}"\n'
        '_N_SUFFIX = 16384\n'
        'N = 16384\n'
        'assert N == _N_SUFFIX, f"PROT-018: anchor _n{_N_SUFFIX} but N={N}"\n'
        'RUN_MODE = ("smoke" if "--smoke" in sys.argv else os.environ.get("HDLAB_RUN_MODE", "full")).lower()\n'
        '_ap = argparse.ArgumentParser()\n'
        '_ap.add_argument("--smoke", action="store_true")\n'
        '_ap.add_argument("--self-test", action="store_true")\n'
        '_ARGS, _ = _ap.parse_known_args()\n'
        'ALPHA_C = 0.138\n'
        f'L_DEPTH = {L}\n'
        'HP_FIDELITY_UNANI_THRESH = 0.9999\n'
        'MIDDLE_FIDELITY = 0.85\n'
        'HF_FIDELITY = 0.85\n'
        'HP_LACC = 0.5\n'
        'HF_LACC = 0.5\n'
        'NOISE_FRAC = 0.10\n'
        '_W_ONDEMAND_GB = 16384 * 16384 * 4 / 1e9\n'
        'assert _W_ONDEMAND_GB < 1.2, f"W on-demand: {_W_ONDEMAND_GB:.3f} GB"\n'
        'if RUN_MODE == "smoke":\n'
        '    N_ACTIVE = 512; SEEDS = [7, 17]; M_INNER = 20\n'
        f'    M_MID = {smoke_mid}\n'
        '    M_OUTER = 2; N_QUERIES = 2\n'
        'else:\n'
        '    N_ACTIVE = N; SEEDS = [7, 17, 23, 31, 41]; M_INNER = 100\n'
        f'    M_MID = {full_mid}\n'
        '    M_OUTER = 2; N_QUERIES = 2\n'
        'assert len(M_MID) == L_DEPTH - 2, f"M_MID {len(M_MID)} expected {L_DEPTH-2}"\n'
        '\n'
        'def _selftest_lN_chain():\n'
        '    n_ctx = L_DEPTH - 1\n'
        '    base = [[1.0, -1.0], [-1.0, 1.0], [1.0, 1.0], [-1.0, -1.0]]\n'
        '    ctxs = [torch.tensor(base[i % 4], dtype=torch.float32, device=DEVICE) for i in range(n_ctx)]\n'
        '    xi_L1 = torch.tensor([1.0, -1.0], dtype=torch.float32, device=DEVICE)\n'
        '    xi = xi_L1.clone()\n'
        '    for c in ctxs: xi = c * xi\n'
        '    xi_dec = xi.clone()\n'
        '    for c in reversed(ctxs): xi_dec = xi_dec * c\n'
        '    assert torch.allclose(xi_dec, xi_L1, atol=1e-6), f"L{L_DEPTH} chain decode failed"\n'
        '\n'
        'def _instrumentation_selftest():\n'
        '    _selftest_lN_chain()\n'
        '    n_dim = N_ACTIVE\n'
        '    ms = [M_INNER] + M_MID + [M_OUTER]\n'
        '    assert len(ms) == L_DEPTH\n'
        '    for i, m in enumerate(ms, 1):\n'
        '        al = m / n_dim\n'
        '        assert al < ALPHA_C, f"L{i} alpha {al:.4f} >= alpha_c"\n'
        '    dummy = torch.zeros((512, 512), device=DEVICE, dtype=torch.float32)\n'
        '    assert torch.cuda.memory_allocated(0) > 0; del dummy\n'
        '    print(f"[selftest] PASS L{L_DEPTH} N={n_dim}", flush=True)\n'
        '\n'
        '_instrumentation_selftest()\n'
        'if _ARGS.self_test: sys.exit(0)\n'
        '\n'
        'def hopfield_retrieve_gpu(W, probe, n_steps=5):\n'
        '    state = probe.clone()\n'
        '    for _ in range(n_steps):\n'
        '        h = W @ state; state = torch.sign(h); state[state == 0] = 1.0\n'
        '    return state\n'
        '\n'
        'def cosine_sim_gpu(a, b):\n'
        '    na, nb = float(a.norm()), float(b.norm())\n'
        '    if na < 1e-12 or nb < 1e-12: return 0.0\n'
        '    return float(torch.dot(a, b)) / (na * nb)\n'
        '\n'
        'def run_seed(seed: int, n_dim: int) -> Dict:\n'
        '    gen = torch.Generator(device=DEVICE); gen.manual_seed(seed); t0 = time.time()\n'
        '    def bsc(m, n_d): return (torch.randint(0,2,(m,n_d),generator=gen,device=DEVICE).float()*2-1)\n'
        '    Xi_inner = bsc(M_INNER, n_dim)\n'
        '    Xi_layers = [Xi_inner]; Xi_ctxs = []; curr = Xi_inner\n'
        '    for i, m in enumerate(M_MID):\n'
        '        ctx = bsc(m, n_dim); Xi_ctxs.append(ctx)\n'
        '        mid = ctx * curr[:m]; Xi_layers.append(mid); curr = mid\n'
        '    ctx_outer = bsc(M_OUTER, n_dim); Xi_ctxs.append(ctx_outer)\n'
        '    Xi_outer = ctx_outer * curr[:M_OUTER]; Xi_layers.append(Xi_outer)\n'
        '    assert len(Xi_layers) == L_DEPTH\n'
        '    print(f"  [seed={seed} N={n_dim}] gpu_mem={torch.cuda.memory_allocated(0)/1e9:.3f}GB", flush=True)\n'
        '    level_fids = {f"L{l}": [] for l in range(1, L_DEPTH+1)}; l_acc = []\n'
        '    for q_idx in range(min(N_QUERIES, M_OUTER)):\n'
        '        xi_outer_true = Xi_outer[q_idx]; probe = xi_outer_true.clone()\n'
        '        flip_mask = (torch.rand(n_dim,generator=gen,device=DEVICE) < NOISE_FRAC)\n'
        '        probe[flip_mask] *= -1.0; decoded = [None] * L_DEPTH\n'
        '        W_top = (Xi_layers[L_DEPTH-1].t() @ Xi_layers[L_DEPTH-1]) / n_dim\n'
        '        ret = hopfield_retrieve_gpu(W_top, probe); del W_top\n'
        '        decoded[L_DEPTH-1] = ret; level_fids[f"L{L_DEPTH}"].append(cosine_sim_gpu(ret, xi_outer_true))\n'
        '        for l_idx in range(L_DEPTH-2, -1, -1):\n'
        '            l_label = l_idx + 1\n'
        '            ptr = decoded[l_idx+1] * Xi_ctxs[l_idx][q_idx]\n'
        '            W_l = (Xi_layers[l_idx].t() @ Xi_layers[l_idx]) / n_dim\n'
        '            ret_l = hopfield_retrieve_gpu(W_l, ptr); del W_l\n'
        '            decoded[l_idx] = ret_l\n'
        '            level_fids[f"L{l_label}"].append(cosine_sim_gpu(ret_l, Xi_layers[l_idx][q_idx]))\n'
        '        l_acc.append(cosine_sim_gpu(decoded[0], Xi_layers[0][q_idx]))\n'
        '    mean_fids = {k: float(sum(v)/len(v)) if v else 0.0 for k, v in level_fids.items()}\n'
        '    mean_lacc = float(sum(l_acc)/len(l_acc)) if l_acc else 0.0\n'
        '    peak_mem = torch.cuda.max_memory_allocated(0) / 1e9; elapsed = time.time() - t0\n'
        '    print(f"  [seed={seed}] l{L_DEPTH}_acc={mean_lacc:.4f} peak_gpu={peak_mem:.3f}GB elapsed={elapsed:.2f}s", flush=True)\n'
        f'    result = {{"seed": seed, "N": n_dim, "run_mode": RUN_MODE, f"l{{L_DEPTH}}_accuracy": float(mean_lacc),\n'
        '              "peak_gpu_gb": float(peak_mem), "elapsed_s": elapsed}\n'
        '    for k, v in mean_fids.items(): result[f"fid_{k.lower()}"] = v\n'
        '    return result\n'
        '\n'
        'def compute_verdict(results: List[Dict]) -> tuple:\n'
        '    if not results: return ("HARD_FAIL", "No valid results.")\n'
        '    def mean_key(k):\n'
        '        vs = [r[k] for r in results if k in r]; return float(sum(vs)/len(vs)) if vs else 0.0\n'
        f'    fid_vals = {{f"L{{l}}": mean_key(f"fid_l{{l}}") for l in range(1, L_DEPTH+1)}}\n'
        f'    lacc = mean_key(f"l{{L_DEPTH}}_accuracy")\n'
        '    fid_list = [fid_vals[f"L{l}"] for l in range(1, L_DEPTH+1)]\n'
        f'    summary = f"l{{L_DEPTH}}_acc={{lacc:.4f}} n_seeds={{len(results)}}"\n'
        '    if any(f < HF_FIDELITY for f in fid_list) or lacc < HF_LACC:\n'
        f'        return ("HARD_FAIL", f"HARD_FAIL: fid/lacc below threshold. {{summary}}")\n'
        '    if all(f >= HP_FIDELITY_UNANI_THRESH for f in fid_list) and lacc >= HP_LACC:\n'
        f'        return ("HARD_PASS", f"HARD_PASS: all {{L_DEPTH}} levels EXACT-1.0 at N={{N}}. {{summary}}")\n'
        '    if any(f < MIDDLE_FIDELITY for f in fid_list):\n'
        f'        return ("MIDDLE_BAND", f"MIDDLE_BAND: graceful degradation. {{summary}}")\n'
        f'    return ("MIDDLE_BAND", f"MIDDLE_BAND: some fids in [{{MIDDLE_FIDELITY}},1.0). {{summary}}")\n'
        '\n'
        'def _prot018_startup_check(n_actual):\n'
        '    if RUN_MODE == "smoke": return\n'
        '    if n_actual != _N_SUFFIX: raise RuntimeError(f"PROT-018: N mismatch {n_actual} vs {_N_SUFFIX}")\n'
        '\n'
        'print(f"[config] N={N} n_active={N_ACTIVE} mode={RUN_MODE} L={L_DEPTH}", flush=True)\n'
        '_prot018_startup_check(N_ACTIVE if RUN_MODE == "smoke" else N)\n'
        'out_dir = get_output_dir(ANCHOR_NAME)\n'
        'run_config = {"N": N, "L": L_DEPTH, "run_mode": RUN_MODE}\n'
        'done, remaining = resumable_seeds(SEEDS, out_dir, run_config=run_config)\n'
        'print(f"[ckpt] {len(done)} done, {len(remaining)} to run", flush=True)\n'
        't_sweep_start = time.time()\n'
        'for seed in remaining:\n'
        '    print(f"[seed={seed}] {ANCHOR_NAME}...", flush=True)\n'
        '    result = run_seed(seed, N_ACTIVE if RUN_MODE == "smoke" else N)\n'
        '    write_partial(out_dir, seed, result)\n'
        'per_seed = aggregate_partials(out_dir, SEEDS)\n'
        'all_results = list(per_seed.values())\n'
        'verdict, verdict_msg = compute_verdict(all_results)\n'
        'print(f"\\n[VERDICT] {verdict}: {verdict_msg}", flush=True)\n'
        'elapsed_total = time.time() - t_sweep_start\n'
        'peak_mem_gb = torch.cuda.max_memory_allocated(0) / 1e9\n'
        'print(f"[GPU] peak memory: {peak_mem_gb:.3f} GB", flush=True)\n'
        'assert peak_mem_gb > 0.01, f"GPU util check FAIL: {peak_mem_gb:.3f}GB"\n'
        f'metrics = {{"anchor_name": ANCHOR_NAME, "verdict": verdict, "verdict_msg": verdict_msg,\n'
        '    "N": N, "L": L_DEPTH, "run_mode": RUN_MODE, "n_seeds": len(SEEDS), "elapsed_s": elapsed_total,\n'
        f'    "per_seed": [{{"seed": r.get("seed"), "lacc": r.get(f"l{{L_DEPTH}}_accuracy"), "elapsed_s": r.get("elapsed_s")}} for r in all_results]}}\n'
        'metrics_path = out_dir / "metrics.json"\n'
        'metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")\n'
        'print(f"[metrics] written to {metrics_path}", flush=True)\n'
    )


if __name__ == "__main__":
    # test smoke_tail/full_tail math
    for L in [128, 129, 130, 131, 132]:
        smoke_tail = L - 5
        full_tail = L - 7
        smoke_mid_len = 3 + smoke_tail
        full_mid_len = 5 + full_tail
        assert smoke_mid_len == L - 2, f"smoke {L}: {smoke_mid_len} != {L-2}"
        assert full_mid_len == L - 2, f"full {L}: {full_mid_len} != {L-2}"
        print(f"L={L} N=16384: smoke_mid={smoke_mid_len} full_mid={full_mid_len} (expected {L-2}) OK")
    for L in [89, 90, 91, 92, 93]:
        smoke_tail = L - 5
        full_tail = L - 7
        smoke_mid_len = 3 + smoke_tail
        full_mid_len = 5 + full_tail
        assert smoke_mid_len == L - 2, f"smoke {L}: {smoke_mid_len} != {L-2}"
        assert full_mid_len == L - 2, f"full {L}: {full_mid_len} != {L-2}"
        print(f"L={L} N=8192: smoke_mid={smoke_mid_len} full_mid={full_mid_len} (expected {L-2}) OK")
    print("All self-tests PASS")
