import sys, json, os
sys.path.insert(0, r"D:\AI\hd-instrument")
from tools.capability_registry_audit import load_registry, write_registry, REGISTRY

NOW = "2026-08-12T00:00:00Z"

new_rows = [
{
 "id": "lexical_similarity_concept_canonicalization_organ",
 "name": "hdlab/lexical_similarity.py -- concept_similarity/concept_vector canonicalization organ (noun/concept similarity + grounded fallback), the entity-canonicalization dependency of the grounding line",
 "kind": "hdlab-module",
 "path": ["hdlab/lexical_similarity.py"],
 "status": "registered_2026-08-12_skunkworks_audit_gap_close",
 "gate_decision": "WIRE",
 "gate_decision_target": "Live-imported by 23 consumers (measured via tools/integration_health.compute_import_graph, independent of the 23-count cited in notes/reinvention_and_registry_audit_2026-08-12.md, matches). Core dependency of hdlab/goal_typing.py, hdlab/quality_relation.py, hdlab/word_acquisition_loop.py, hdlab/reading_grounding_loop.py, hdlab/grounded_similarity.py. Closes a pre-existing registry gap (flagged by name in row grounded_word_acquisition_loop_increment1s own notes_registry_gap field).",
 "integration_status": "WIRED",
 "used_by": [],
 "revival_criteria": "",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "open-vocab noun/concept pairwise similarity via shared-feature representation, with grounded (Lancaster/Brysbaert) fallback for OOV concepts.",
 "provenance": "MEASURED@data/exp_n11c_shared_feature_lexical_similarity_v1/metrics.json (verdict=HARD_PASS, ordered_frac 0.966 shared-feature vs 0.379 window / 0.103 hash / 0.310 scramble controls, disk-verified this session) + MEASURED@data/exp_grounded_meaning_wire_lexical_fallback_v1/metrics.json (verdict=HARD_PASS_grounded_meaning_wired_without_over_merge, disk-verified this session). Consumer count (23) independently recomputed via tools/integration_health.compute_import_graph, not taken from the prior triage notes figure.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_AND_PIPELINE_USED",
},
{
 "id": "grounded_similarity_perceptual_fallback_organ",
 "name": "hdlab/grounded_similarity.py -- Lancaster sensorimotor + Brysbaert concreteness perceptual-grounding FALLBACK feature space, additive to lexical_similarity, never replacing it",
 "kind": "hdlab-module",
 "path": ["hdlab/grounded_similarity.py"],
 "status": "registered_2026-08-12_skunkworks_audit_gap_close",
 "gate_decision": "WIRE",
 "gate_decision_target": "Directly imported by hdlab/lexical_similarity.py (use_grounded_fallback=True path), the dependency the lexical_similarity WIRE decision relies on. 5 total consumers measured via tools/integration_health.",
 "integration_status": "WIRED",
 "used_by": [],
 "revival_criteria": "",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "OOV-word grounded similarity fallback (39707-word Lancaster+Brysbaert norms) when a word is absent from the hand-typed CONCEPT_FEATURES lexicon.",
 "provenance": "MEASURED@data/exp_grounded_meaning_wire_lexical_fallback_v1/metrics.json (verdict=HARD_PASS_grounded_meaning_wired_without_over_merge, disk-verified this session). Module docstring explicitly frames this as strict-ADD fallback, checked against hdlab/lexical_similarity.py:599 call site.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_AND_PIPELINE_USED",
},
{
 "id": "random_indexing_open_vocab_encoder",
 "name": "hdlab/random_indexing.py -- RandomIndexingEncoder, open-vocabulary distributional HD encoder (Sahlgren 2005)",
 "kind": "hdlab-module",
 "path": ["hdlab/random_indexing.py"],
 "status": "registered_2026-08-12_skunkworks_audit_VET_PENDING",
 "gate_decision": "VET_PENDING",
 "gate_decision_target": "Built and live-imported by 5 experiment cells (measured), but the modules OWN direct-import verdicts are mixed, no clean HARD_PASS: exp_n11_random_indexing_semantic_v1=MIDDLE_BAND, exp_n11b_symmetric_pattern_lexical_similarity_v1=HARD_FAIL, exp_sense_collapse_floor_v1=MEASURED (non pass/fail), exp_context_conditioned_sense_selection_v1=HARD_FAIL_context_conditioned_sense_selection_DOES_NOT_WORK (all 4 verdicts disk-verified this session). exp_learned_codebook_generalization_gate_v1 cites it in a comment as reused concept/math but does NOT literally import it (reimplemented inline as ri_raw arm, AUC=0.738, weakest of 3 codebook variants tested). Default-NOT-WIRE applied: real, used, but no evidenced win of its own to cite.",
 "integration_status": "TRAPPED_SHARED",
 "used_by": [],
 "revival_criteria": "A cell that imports hdlab.random_indexing.RandomIndexingEncoder directly and lands HARD_PASS off it (not an inline reimplementation) would justify WIRE.",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "not established, see gate_decision_target",
 "provenance": "5 consumers measured via tools/integration_health.compute_import_graph. Verdicts pulled fresh from each consumers data/<anchor>/metrics.json this session.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
{
 "id": "reading_grounding_loop_definitional_reading_pipeline",
 "name": "hdlab/reading_grounding_loop.py -- canonicalize()+store() reading/grounding pipeline (flat-cosine sense match + hd_fact_store write), core module of the active grounding arc",
 "kind": "hdlab-module",
 "path": ["hdlab/reading_grounding_loop.py"],
 "status": "registered_2026-08-12_skunkworks_audit_gap_close_with_caveat",
 "gate_decision": "WIRE",
 "gate_decision_target": "5 live consumers measured (exp_reading_grounding_loop_cycle1_v1=HARD_PASS, cycle2_v1=HARD_PASS, cycle3_groundingfix_v1=STRUCTURAL_PASS_PENDING_B3, exp_gap_driven_reader_controlled_v1=HARD_PASS, exp_definitional_grounding_v3=STRUCTURAL_PASS_PENDING_B3, all 5 disk-verified this session). Owned by a concurrent session; this row registers the MODULEs integration status only, does not edit the file. CAVEAT (symmetric anti-negativity, per notes/foundation_grounding_sample_2026-08-12.md and MEMORY.md 2026-08-12 entry): the plumbing (read/store/persist/retrieve) is proven, but a later independent audit found the grounded concepts claim materially overstated (65.7 percent self-referential tautologies, prior HARD_PASS partly circular). WIRE reflects the module being real, live, load-bearing infrastructure, it does NOT re-certify the downstream grounding-quality claim, which remains under revision by the owning session.",
 "integration_status": "TRAPPED_SHARED",
 "used_by": [],
 "revival_criteria": "",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "reading-time word-sense canonicalization + fact-store write for the definitional-grounding arc; see caveat before citing its output as validated MEANING grounding.",
 "provenance": "5 consumers measured via tools/integration_health.compute_import_graph; 5 verdicts pulled fresh from each consumers metrics.json this session.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
{
 "id": "semantic_trace_bus_emit_helpers",
 "name": "hdlab/semantic.py -- Layer-2 trace-bus semantic emit helpers (connection-logic WHY events), distinct job from hdlab/semantic_parser.py M1.9 intent/role-slot extraction",
 "kind": "hdlab-module",
 "path": ["hdlab/semantic.py"],
 "status": "registered_2026-08-12_skunkworks_audit_gap_close",
 "gate_decision": "WIRE",
 "gate_decision_target": "Imported by hdlab/__init__.py, hdlab/ablation.py, hdlab/tracing.py (core tracing subsystem, loaded on every hdlab import) plus experiments/exp_traceable_multi_hop.py (4 consumers measured). CONTENT-DIFF vs hdlab/semantic_parser.py performed this session (task priority-3 duplicate check): NOT a duplicate, semantic.py (121 lines) is trace-bus observability plumbing; semantic_parser.py (698 lines, already registered as a separate row) is the M1.9 SemanticParser cortex primitive (intent+role-slot extraction over pre-composed HD bundles). Disjoint jobs, genuinely different code.",
 "integration_status": "WIRED",
 "used_by": [],
 "revival_criteria": "",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "emitting WHY-level semantic trace events (entity cleanup, relation activation, edge/modulator) on top of the operator-level trace bus.",
 "provenance": "4 consumers measured via tools/integration_health.compute_import_graph. Part of the tracing subsystem verification/run_certification.py gates on tracing=False (CLAUDE.md verification discipline), not independently re-run this session, cert status inherited from the tracing subsystems own gate.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_AND_PIPELINE_USED",
},
{
 "id": "compose_freq_routing_promoted_zero_consumer",
 "name": "hdlab/compose_freq_routing.py -- compose-frequency associative-trace gate, promoted from Stage-2 substrate_compose_freq_routing v5 DEFINITIVE (5-seed cross-N HARD_PASS_CHAIN_GRADE_DEFINITIVE 2026-06-25)",
 "kind": "hdlab-module",
 "path": ["hdlab/compose_freq_routing.py"],
 "status": "registered_2026-08-12_skunkworks_audit_zero_consumer",
 "gate_decision": "SHELVE",
 "gate_decision_target": "Zero live consumers measured (tools/integration_health.compute_import_graph). Parent cell has real prior CG evidence, but that evidence certifies the PARENT experiment, not that this promoted hdlab module is consumed by anything today, default-NOT-WIRE applied per this tasks instruction.",
 "integration_status": "ISLAND",
 "used_by": [],
 "revival_criteria": "Wire when a live consumer needs composition-frequency gating of stored associative traces (e.g. a cortex/hippocampus integration cell).",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "not currently consumed",
 "provenance": "MEASURED zero consumers via tools/integration_health.compute_import_graph this session; parent cell evidence cited in module docstring (EXP_substrate_compose_freq_routing_v5_DEFINITIVE), not independently re-verified this session (out of scope, consumer-graph check only).",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
{
 "id": "excitability_tensor_promoted_zero_consumer",
 "name": "hdlab/excitability.py -- substrate-native excitability tensor E[i] (per-atom importance signal, CREB / synaptic-tag-and-capture brain analog)",
 "kind": "hdlab-module",
 "path": ["hdlab/excitability.py"],
 "status": "registered_2026-08-12_skunkworks_audit_zero_consumer",
 "gate_decision": "SHELVE",
 "gate_decision_target": "Zero live consumers measured (tools/integration_health.compute_import_graph). Default-NOT-WIRE applied.",
 "integration_status": "ISLAND",
 "used_by": [],
 "revival_criteria": "Wire when a live cortex-class consumer needs an importance signal orthogonal to weight magnitude.",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "not currently consumed",
 "provenance": "MEASURED zero consumers via tools/integration_health.compute_import_graph this session.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
{
 "id": "profiling_op_latency_zero_consumer",
 "name": "hdlab/profiling.py -- per-op latency/FLOPs/memory-access profiling helpers for hardware-substrate analysis (Week 4/8)",
 "kind": "hdlab-module",
 "path": ["hdlab/profiling.py"],
 "status": "registered_2026-08-12_skunkworks_audit_zero_consumer",
 "gate_decision": "SHELVE",
 "gate_decision_target": "Zero live consumers measured (tools/integration_health.compute_import_graph). Infra utility, not a research claim, no verdict to cite either way. Default-NOT-WIRE applied.",
 "integration_status": "ISLAND",
 "used_by": [],
 "revival_criteria": "Wire when Week-8-class hardware analysis (per module docstring) actually begins and needs persisted per-op profiling.",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "not currently consumed",
 "provenance": "MEASURED zero consumers via tools/integration_health.compute_import_graph this session.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
{
 "id": "self_manager_neuromodulatory_zero_consumer",
 "name": "hdlab/self_manager.py -- bank of content-free scalar meta-controllers (6 neuromodulatory-channel analogs) over the certified value/attention gates",
 "kind": "hdlab-module",
 "path": ["hdlab/self_manager.py"],
 "status": "registered_2026-08-12_skunkworks_audit_zero_consumer",
 "gate_decision": "SHELVE",
 "gate_decision_target": "Zero live consumers measured (tools/integration_health.compute_import_graph). Default-NOT-WIRE applied, do not wire a self-tuning controller bank with no consumer sight-unseen.",
 "integration_status": "ISLAND",
 "used_by": [],
 "revival_criteria": "Wire only once a specific certified value-gate/attention-gate consumer is identified that needs gain/threshold/horizon self-tuning, and that consumers own behavior is measured with the controller on vs off.",
 "supersedes": None,
 "superseded_by": None,
 "current_best_for": "not currently consumed",
 "provenance": "MEASURED zero consumers via tools/integration_health.compute_import_graph this session.",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
{
 "id": "scratch_orig_goal_owner_select_stale_backup",
 "name": "hdlab/_scratch_orig_goal_owner_select.py -- stale pre-promotion backup copy of hdlab/goal_owner_select.py (docstring literally names the other file)",
 "kind": "hdlab-module",
 "path": ["hdlab/_scratch_orig_goal_owner_select.py"],
 "status": "registered_2026-08-12_skunkworks_audit_DEAD_superseded",
 "gate_decision": "SHELVE",
 "gate_decision_target": "DEAD/superseded, not a revival candidate. Diff against hdlab/goal_owner_select.py shows a near-full-file delta (113 diff lines out of 121); the scratch files own docstring header reads hdlab/goal_owner_select.py, this is a backup snapshot left from the 2026-08-05 promotion edit, not an independent module. Zero consumers measured. Recommend deletion on a future cleanup pass; not registering as WIRE or VET_PENDING under any circumstance.",
 "integration_status": "ISLAND",
 "used_by": [],
 "revival_criteria": "None, superseded. Delete-candidate, not revival-candidate.",
 "supersedes": None,
 "superseded_by": "goal_owner_select_component5_directed_score",
 "current_best_for": "N/A, dead backup file",
 "provenance": "MEASURED zero consumers via tools/integration_health.compute_import_graph this session; content diff against hdlab/goal_owner_select.py run this session (113 diff lines out of 121 in the scratch file).",
 "last_audit_utc": NOW,
 "last_decision_utc": NOW,
 "pipeline_status": "WIRED_BUT_NOT_PIPELINE_REACHABLE",
},
]

rows = load_registry()
before = len(rows)
ids_before = {r["id"] for r in rows}
new_ids = {r["id"] for r in new_rows}
dup = new_ids & ids_before
assert not dup, "duplicate ids: %r" % (dup,)
assert len(new_ids) == len(new_rows), "duplicate ids within new_rows"

rows_out = rows + new_rows
write_registry(rows_out)

reloaded = load_registry()
assert len(reloaded) == before + len(new_rows), (len(reloaded), before, len(new_rows))
reloaded_ids = {r["id"] for r in reloaded}
for nid in new_ids:
    assert nid in reloaded_ids, nid
print("OK: before=%d after=%d added=%d" % (before, len(reloaded), len(new_rows)))
