#!/usr/bin/env python3
"""Item 4 v2.1 catalog reconcile APPLY tool.

Reads data/item_4_reconcile_patch_v2_2026-06-19.json (generated by
item_4_catalog_reconcile_patch_v2.py with Skunkworks-VET'd missed-binds added).

Applies metadata-only mutations in-place by:
1. Loading the partition's atoms.jsonl
2. Locating each target atom by id
3. Rewriting its fields per patch (composes_with cleaned + memory_references
   added + conceptual_references added + cross_ref_annotations added if any)
4. Atomically writing partition back (write tmp + os.replace)
5. RAW JSONL re-read verification (no get_atom; no silent-fail risk)

Per Skunkworks SCHEMA-VET v1 PASS + Q1=B + Q2 + Skunkworks per-bind VET
(net 12-13 bound / 5-6 unbound; 4 missed-binds added at confidence=99).

A5-SAFE: tier/pq/relevance untouched; only metadata fields patched.
Snapshot-before captured (count + atom-id list).
"""

import json
import os
import shutil
from pathlib import Path

ROOT = Path("data/substrate_index")
PATCH_FILE = Path("data/item_4_reconcile_patch_v2_2026-06-19.json")


def load_patch():
    with PATCH_FILE.open(encoding="utf-8") as f:
        return json.load(f)


def find_partition_for_atom(atom_id):
    """Scan partitions to find which one contains atom_id."""
    for atoms_file in ROOT.glob("*/atoms.jsonl"):
        with atoms_file.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    a = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if a.get("id") == atom_id:
                    return atoms_file
    return None


def apply_patch_to_atom(atom_dict, patch):
    """Mutate atom_dict in-place per patch entry.

    PER SKUNKWORKS MUST-FIX (2026-06-19 landed-VET): memory_references +
    conceptual_references + cross_ref_annotations MUST live in metadata
    (schema-preserved by Atom.to_dict()); top-level placement = silent-loss
    on next Store-native flush (the recurring Store-drops-unmodeled-fields
    lesson, generalizing the edge_metadata_role lesson).

    Sets:
    - composes_with / parent_of / etc. -> field_new_values (cleaned).
      These already live in metadata for AUDIT_LESSON atoms; write to both
      top-level AND metadata for backwards-compat (whoever reads first gets
      consistent state; to_dict preserves metadata).
    - metadata.memory_references += memory_references_new (deduplicated).
    - metadata.conceptual_references += conceptual_references_new (dedup by value).
    - metadata.cross_ref_annotations += cross_ref_annotations_new (if any).
    - REMOVES any TOP-LEVEL placement of these 3 fields (cleanup from v2.1
      first-pass which wrote them top-level).
    """
    md = atom_dict.get("metadata") or {}

    # Apply field_new_values (cleaned cross-ref fields)
    for field, new_vals in patch.get("field_new_values", {}).items():
        atom_dict[field] = new_vals
        # If the field already lives in metadata (AUDIT_LESSON pattern), mirror
        if field in md:
            md[field] = new_vals

    # Memory_references -> metadata.memory_references (NOT top-level)
    if patch.get("memory_references_new"):
        # First sweep up any stale top-level placement (clean-up the first-pass)
        existing_top = atom_dict.pop("memory_references", None) or []
        existing_md = md.get("memory_references") or []
        merged = sorted(set(existing_top) | set(existing_md) |
                        set(patch["memory_references_new"]))
        md["memory_references"] = merged

    # Conceptual_references -> metadata.conceptual_references (NOT top-level)
    if patch.get("conceptual_references_new"):
        existing_top = atom_dict.pop("conceptual_references", None) or []
        existing_md = md.get("conceptual_references") or []
        existing_values = set()
        merged = []
        for entry in list(existing_top) + list(existing_md):
            val = entry.get("value") if isinstance(entry, dict) else entry
            if val not in existing_values:
                merged.append(entry)
                existing_values.add(val)
        for entry in patch["conceptual_references_new"]:
            val = entry.get("value") if isinstance(entry, dict) else entry
            if val not in existing_values:
                merged.append(entry)
                existing_values.add(val)
        md["conceptual_references"] = merged

    # Cross_ref_annotations -> metadata.cross_ref_annotations (NOT top-level)
    if patch.get("cross_ref_annotations_new"):
        existing_top = atom_dict.pop("cross_ref_annotations", None) or []
        existing_md = md.get("cross_ref_annotations") or []
        md["cross_ref_annotations"] = (list(existing_top) + list(existing_md)
                                       + list(patch["cross_ref_annotations_new"]))

    # IMPORTANT cleanup: remove top-level placements from prior v2.1 first-pass
    # (silent-loss prevention; the relocation MUST clean up the stale top-level
    # state so a future Store-native flush doesn't silently drop them and a
    # raw-JSONL inspector doesn't see two copies)
    for key in ("memory_references", "conceptual_references",
                "cross_ref_annotations"):
        atom_dict.pop(key, None)

    atom_dict["metadata"] = md
    return atom_dict


def rewrite_partition(partition_path, patches_for_atoms):
    """Rewrite a partition file with the patched atoms.

    Reads each line, applies patch if atom_id is in patches_for_atoms, writes
    back to a tmp file, then atomically os.replace.
    """
    tmp = partition_path.with_suffix(".jsonl.tmp")
    n_patched = 0
    n_lines = 0
    with partition_path.open(encoding="utf-8") as src, \
         tmp.open("w", encoding="utf-8") as dst:
        for line in src:
            stripped = line.strip()
            if not stripped:
                dst.write(line)
                continue
            try:
                atom = json.loads(stripped)
            except json.JSONDecodeError:
                dst.write(line)
                continue
            n_lines += 1
            atom_id = atom.get("id")
            if atom_id in patches_for_atoms:
                atom = apply_patch_to_atom(atom, patches_for_atoms[atom_id])
                n_patched += 1
            dst.write(json.dumps(atom, ensure_ascii=False) + "\n")
    os.replace(tmp, partition_path)
    return n_patched, n_lines


def verify_atom_post_patch(atom_id, expected_patch):
    """RAW jsonl re-read to verify patch landed. No get_atom; no silent-fail.

    Per Skunkworks MUST-FIX: verify the new fields live in METADATA (not top
    level). Also verify there is NO top-level placement (cleanup confirmation).
    """
    for atoms_file in ROOT.glob("*/atoms.jsonl"):
        with atoms_file.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    a = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if a.get("id") == atom_id:
                    md = a.get("metadata") or {}

                    # Cleanup verification: NO top-level placement
                    for key in ("memory_references", "conceptual_references",
                                "cross_ref_annotations"):
                        if key in a:
                            return False, (f"TOP-LEVEL {key} still present "
                                           f"(silent-loss risk; must be in metadata only)")

                    # Check memory_references in METADATA
                    expected_mem = set(expected_patch.get(
                        "memory_references_new", []))
                    actual_mem = set(md.get("memory_references") or [])
                    if expected_mem and not expected_mem.issubset(actual_mem):
                        return False, (f"metadata.memory_references missing: "
                                       f"expected {expected_mem - actual_mem}")

                    # Check conceptual_references in METADATA (by value)
                    expected_concepts = set()
                    for entry in expected_patch.get(
                            "conceptual_references_new", []):
                        val = entry.get("value") if isinstance(entry, dict) else entry
                        expected_concepts.add(val)
                    actual_concepts = set()
                    for entry in (md.get("conceptual_references") or []):
                        val = entry.get("value") if isinstance(entry, dict) else entry
                        actual_concepts.add(val)
                    if expected_concepts and not expected_concepts.issubset(
                            actual_concepts):
                        return False, (f"metadata.conceptual_references missing: "
                                       f"{expected_concepts - actual_concepts}")

                    # Check composes_with cleaned (top-level OR metadata is OK; both mirror)
                    new_composes = expected_patch.get(
                        "field_new_values", {}).get("composes_with")
                    if new_composes is not None:
                        actual_composes = a.get("composes_with") or []
                        if set(new_composes) != set(actual_composes):
                            return False, (f"composes_with mismatch: expected "
                                           f"{set(new_composes)} got {set(actual_composes)}")
                    return True, "OK"
    return False, "atom not found"


def main():
    print("=" * 80)
    print("ITEM 4 v2.1 CATALOG RECONCILE APPLY (Skunkworks-VET'd)")
    print("=" * 80)
    print()

    if not PATCH_FILE.exists():
        print(f"ERROR: patch file missing: {PATCH_FILE}")
        return

    patch_data = load_patch()
    patches = patch_data.get("patches", {})
    print(f"Patches to apply: {len(patches)}")
    print(f"Schema version: {patch_data.get('schema_version')}")
    print(f"Scope: {patch_data.get('scope')}")
    print()

    # Snapshot-before
    print("Snapshot-before (count + ids):")
    snapshot_before_ids = sorted(patches.keys())
    print(f"  patched atom-ids count: {len(snapshot_before_ids)}")
    print(f"  first 5 ids: {snapshot_before_ids[:5]}")
    print()

    # Group patches by partition (efficiency: rewrite each partition once)
    print("Locating partitions for patched atoms...")
    by_partition = {}
    not_found = []
    for atom_id in patches:
        p = find_partition_for_atom(atom_id)
        if p is None:
            not_found.append(atom_id)
            continue
        by_partition.setdefault(p, {})[atom_id] = patches[atom_id]

    if not_found:
        print(f"WARNING: {len(not_found)} atoms not found in any partition:")
        for aid in not_found:
            print(f"  {aid}")
    print()

    # Apply per-partition
    total_patched = 0
    for partition_path, atom_patches in by_partition.items():
        print(f"Rewriting partition: {partition_path.parent.name}/atoms.jsonl "
              f"({len(atom_patches)} atoms)...")
        n_patched, n_lines = rewrite_partition(partition_path, atom_patches)
        print(f"  patched={n_patched}  total_lines={n_lines}")
        total_patched += n_patched

    print()
    print(f"TOTAL patched: {total_patched}")
    print()

    # Verify (RAW jsonl re-read)
    print("=" * 80)
    print("VERIFY (raw jsonl re-read; no get_atom; no silent-fail risk)")
    print("=" * 80)
    n_pass = 0
    n_fail = 0
    failures = []
    for atom_id, patch in patches.items():
        ok, msg = verify_atom_post_patch(atom_id, patch)
        if ok:
            n_pass += 1
        else:
            n_fail += 1
            failures.append((atom_id, msg))
    print(f"PASS: {n_pass}/{len(patches)}")
    print(f"FAIL: {n_fail}/{len(patches)}")
    if failures:
        print()
        print("Failures:")
        for aid, msg in failures[:10]:
            print(f"  {aid}: {msg}")
    print()

    # Cross-check: composes_with phantoms after
    print("Cross-check: counting composes_with-style phantoms after patch...")
    # Skipping full scour here; Skunkworks's S2 invariant-check v1.3 covers it
    # post-patch with the new structured fields.

    print()
    print("APPLY COMPLETE. Route to Skunkworks for landed-VET + S2 v1.3 update.")


if __name__ == "__main__":
    main()
