"""T1 batches 08-12 bulk ingest: 41 absent atoms across numerical linear algebra (08),
optimization (09), measure theory + integration (10), stochastic processes (11),
functional analysis remainder (12).
"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend.substrate_index.partition import PartitionedStore
from backend.substrate_index.schema import Atom, AtomKind, Corpus, Tier


# Concise specs: (id, name, aliases, description, serves_capability tuple, category, signature_hint, batch)
SPECS = [
    # BATCH 08: numerical linear algebra
    ("T1/matrix_decomposition", "Matrix decomposition", ("matrix_factorization",),
     "Factorization A = X * Y * Z structured to expose properties (rank, eigenvalues, etc.). Foundation for SVD/QR/LU/Cholesky.",
     ("numerical_linear_algebra", "matrix_factorization_foundation", "substrate_self_knowledge"),
     "linear_algebra::factorizations", "structured_factorization", "batch_08"),
    ("T1/SVD", "Singular value decomposition", ("singular_value_decomposition", "U_Sigma_V_T"),
     "A = U Sigma V^T with U,V orthogonal + Sigma diagonal non-negative. Foundation for rank + pseudoinverse + low-rank approximation.",
     ("rank_analysis", "low_rank_approximation", "pseudoinverse_construction", "substrate_self_knowledge"),
     "linear_algebra::factorizations", "orthogonal_diagonal_orthogonal", "batch_08"),
    ("T1/eigendecomposition", "Eigendecomposition", ("spectral_decomposition", "A_eq_Q_Lambda_Q_inv"),
     "A = Q Lambda Q^{-1} where Q has eigenvectors as columns + Lambda diagonal of eigenvalues. Foundation for spectral theory.",
     ("spectral_analysis", "diagonalization_foundation", "substrate_self_knowledge"),
     "linear_algebra::spectral", "eigenvector_eigenvalue_diagonalization", "batch_08"),
    ("T1/QR_decomposition", "QR decomposition", ("Gram_Schmidt_factorization",),
     "A = Q R where Q orthogonal + R upper triangular. Foundation for least-squares + numerical stability.",
     ("least_squares_foundation", "numerical_linear_algebra", "substrate_self_knowledge"),
     "linear_algebra::factorizations", "orthogonal_triangular", "batch_08"),
    ("T1/LU_decomposition", "LU decomposition", ("Gauss_elimination_factorization",),
     "A = L U where L lower triangular unit-diag + U upper triangular. Foundation for solving linear systems.",
     ("linear_system_solving", "numerical_linear_algebra", "substrate_self_knowledge"),
     "linear_algebra::factorizations", "lower_upper_triangular", "batch_08"),
    ("T1/cholesky_decomposition", "Cholesky decomposition", ("LL_T", "symmetric_positive_factorization"),
     "Symmetric positive-definite A = L L^T with L lower triangular. Foundation for efficient SPD system solving + Gaussian sampling.",
     ("SPD_system_solving", "gaussian_sampling_foundation", "substrate_self_knowledge"),
     "linear_algebra::factorizations", "symmetric_positive_definite_factorization", "batch_08"),
    ("T1/condition_number", "Condition number", ("kappa_A", "numerical_stability_indicator"),
     "kappa(A) = sigma_max / sigma_min via SVD. Measures linear system sensitivity to perturbations.",
     ("numerical_stability_analysis", "perturbation_bound", "substrate_self_knowledge"),
     "linear_algebra::numerical_analysis", "ratio_of_extreme_singular_values", "batch_08"),
    ("T1/pseudoinverse", "Pseudoinverse", ("Moore_Penrose_inverse", "A_plus"),
     "A^+ = V Sigma^+ U^T via SVD. Solves least-squares min ||Ax - b|| + minimum norm.",
     ("least_squares_solving", "underdetermined_system_solving", "substrate_self_knowledge"),
     "linear_algebra::generalizations", "moore_penrose_via_svd", "batch_08"),
    # BATCH 09: optimization
    ("T1/duality_lagrangian", "Lagrangian duality", ("lagrange_dual", "weak_duality"),
     "Dual problem max_{lambda >= 0} min_x L(x, lambda). Weak duality: primal >= dual. Strong duality under Slater's condition.",
     ("optimization_theory_foundation", "convex_duality", "substrate_self_knowledge"),
     "optimization::duality", "minimax_swap_with_multipliers", "batch_09"),
    ("T1/subgradient", "Subgradient", ("partial_f", "convex_generalization_of_gradient"),
     "For convex non-differentiable f: g is subgradient at x iff f(y) >= f(x) + g . (y - x) for all y.",
     ("non_smooth_optimization", "convex_analysis_foundation", "substrate_self_knowledge"),
     "optimization::convex_analysis", "convex_supporting_hyperplane", "batch_09"),
    ("T1/line_search", "Line search", ("step_size_optimization", "alpha_search"),
     "Find alpha along direction d to minimize/decrease f(x + alpha d). Backtracking + Wolfe + Goldstein conditions.",
     ("iterative_optimization", "step_size_selection", "substrate_self_knowledge"),
     "optimization::iterative_methods", "step_size_search_along_direction", "batch_09"),
    ("T1/trust_region", "Trust region method", ("model_trust_radius",),
     "Iteratively optimize quadratic model within radius Delta; update Delta based on actual vs predicted reduction.",
     ("iterative_optimization", "quadratic_model_optimization", "substrate_self_knowledge"),
     "optimization::iterative_methods", "model_trust_radius_dynamic", "batch_09"),
    ("T1/fixed_point_iteration", "Fixed point iteration", ("Banach_iteration", "x_n_plus_1_eq_T_x_n"),
     "Iterate x_{n+1} = T(x_n) until convergence to fixed point T(x*) = x*. Foundation for contraction mapping + EM + Q-iteration.",
     ("iterative_solving", "convergence_to_fixed_point", "substrate_self_knowledge"),
     "analysis::iterative_methods", "contraction_mapping_iteration", "batch_09"),
    # BATCH 10: measure theory + integration
    ("T1/measurable_function", "Measurable function", ("preimage_in_sigma_algebra",),
     "f: (X, F) -> (Y, G) measurable iff f^{-1}(B) in F for all B in G. Foundation for Lebesgue integration.",
     ("measure_theory_foundation", "integration_foundation", "substrate_self_knowledge"),
     "measure_theory::core_definitions", "preimage_of_measurable_is_measurable", "batch_10"),
    ("T1/lebesgue_integral", "Lebesgue integral", ("integral_w_r_t_measure",),
     "integral f dmu defined via simple function approximation + monotone limit. Generalizes Riemann; handles discontinuous functions.",
     ("integration_theory", "probability_expectation_foundation", "substrate_self_knowledge"),
     "measure_theory::integration", "monotone_limit_of_simple_integrals", "batch_10"),
    ("T1/dominated_convergence_theorem", "Dominated convergence theorem", ("DCT",),
     "If f_n -> f a.e. + |f_n| <= g integrable, then integral f_n -> integral f. Foundation for limit-integral exchange.",
     ("integration_limit_theorem", "interchange_limit_and_integral", "substrate_self_knowledge"),
     "measure_theory::convergence_theorems", "dominated_a_e_pointwise_convergence", "batch_10"),
    ("T1/monotone_convergence_theorem", "Monotone convergence theorem", ("MCT",),
     "If 0 <= f_n increasing a.e. to f, then integral f_n -> integral f. Foundation for Lebesgue integral construction.",
     ("integration_limit_theorem", "monotone_limit_integral", "substrate_self_knowledge"),
     "measure_theory::convergence_theorems", "increasing_a_e_pointwise", "batch_10"),
    ("T1/fubini_tonelli", "Fubini-Tonelli theorem", ("Fubini_theorem",),
     "For integrable / non-negative measurable f: iterated integrals over product space exist + are equal to product integral.",
     ("multivariate_integration", "iterated_integral_exchange", "substrate_self_knowledge"),
     "measure_theory::product_measures", "iterated_integral_equality", "batch_10"),
    ("T1/radon_nikodym", "Radon-Nikodym theorem", ("RN_derivative", "dmu_dnu"),
     "If mu << nu (mu absolutely continuous w.r.t. nu) + sigma-finite, then dmu = (dmu/dnu) dnu for measurable density.",
     ("measure_theory_foundation", "conditional_probability_foundation", "substrate_self_knowledge"),
     "measure_theory::derivatives", "absolutely_continuous_density", "batch_10"),
    ("T1/absolute_continuity_of_measures", "Absolute continuity (measures)", ("mu_ll_nu",),
     "mu << nu iff nu(A) = 0 implies mu(A) = 0. Foundation for Radon-Nikodym derivatives.",
     ("measure_theory_foundation", "RN_derivative_existence", "substrate_self_knowledge"),
     "measure_theory::measure_comparison", "null_set_inclusion", "batch_10"),
    ("T1/almost_everywhere", "Almost everywhere", ("a_e", "modulo_null_set"),
     "Property holds a.e. iff set where it fails has measure zero. Foundation for L^p equivalence classes.",
     ("measure_theory_foundation", "Lp_space_construction", "substrate_self_knowledge"),
     "measure_theory::null_sets", "modulo_null_set", "batch_10"),
    ("T1/sigma_finite", "Sigma-finite measure", ("countable_union_of_finite_measure_sets",),
     "Measure mu sigma-finite iff X = union of countably many sets each with mu(A_i) < infty. Foundation for Radon-Nikodym + Fubini.",
     ("measure_theory_foundation", "RN_FT_existence_condition", "substrate_self_knowledge"),
     "measure_theory::measure_properties", "countable_decomposition_finite_measure", "batch_10"),
    # BATCH 11: stochastic processes
    ("T1/martingale", "Martingale", ("E_X_n_plus_1_given_F_n_eq_X_n",),
     "Process X_n adapted to filtration F_n with E[X_{n+1} | F_n] = X_n. Foundation for stopping times + optional stopping theorem.",
     ("stochastic_process_foundation", "fair_game_modeling", "substrate_self_knowledge"),
     "stochastic_processes::core_classes", "conditional_expectation_equals_current", "batch_11"),
    ("T1/brownian_motion", "Brownian motion", ("Wiener_process", "B_t"),
     "Continuous Gaussian process with B_0=0 + independent increments + B_t-B_s ~ N(0, t-s). Foundation for SDE + diffusion.",
     ("stochastic_process_foundation", "diffusion_modeling", "substrate_self_knowledge"),
     "stochastic_processes::core_classes", "gaussian_independent_increments", "batch_11"),
    ("T1/stationary_distribution", "Stationary distribution", ("pi_P_eq_pi", "invariant_measure"),
     "pi P = pi for Markov chain transition P. Long-run distribution if chain ergodic.",
     ("markov_chain_foundation", "ergodic_theory_foundation", "substrate_self_knowledge"),
     "stochastic_processes::markov_theory", "invariant_under_transition", "batch_11"),
    ("T1/ergodicity", "Ergodicity", ("time_average_eq_space_average",),
     "Property: time average over single sample path equals ensemble average. Foundation for MCMC + statistical sampling.",
     ("stochastic_process_foundation", "MCMC_foundation", "substrate_self_knowledge"),
     "stochastic_processes::ergodic_theory", "time_eq_space_average", "batch_11"),
    ("T1/stopping_time", "Stopping time", ("tau_F_n_adapted",),
     "Random time tau with {tau <= n} in F_n for all n. Foundation for martingale optional stopping + early termination.",
     ("stochastic_process_foundation", "optional_stopping_foundation", "substrate_self_knowledge"),
     "stochastic_processes::core_definitions", "stopping_rule_filtration_adapted", "batch_11"),
    ("T1/ito_integral", "Ito integral", ("stochastic_integral_dB",),
     "integral H_s dB_s defined via L^2 isometry. Foundation for SDE solutions + financial mathematics.",
     ("stochastic_calculus", "SDE_foundation", "substrate_self_knowledge"),
     "stochastic_processes::stochastic_calculus", "L2_isometry_against_brownian", "batch_11"),
    ("T1/sde", "Stochastic differential equation", ("SDE", "dX_t_eq_mu_dt_plus_sigma_dB"),
     "dX_t = mu(X_t, t) dt + sigma(X_t, t) dB_t. Foundation for diffusion processes + DBM + Langevin dynamics.",
     ("stochastic_modeling", "diffusion_dynamics_foundation", "substrate_self_knowledge"),
     "stochastic_processes::sde", "drift_plus_diffusion", "batch_11"),
    ("T1/levy_process", "Levy process", ("infinitely_divisible_independent_increments",),
     "Process with stationary independent increments + cadlag paths + X_0 = 0. Generalizes Brownian + Poisson; Levy-Khintchine triplet.",
     ("stochastic_process_foundation", "jump_diffusion_modeling", "substrate_self_knowledge"),
     "stochastic_processes::core_classes", "stationary_independent_increments", "batch_11"),
    ("T1/poisson_process", "Poisson process", ("counting_process", "N_t_Poisson_lambda_t"),
     "Counting process with rate lambda; inter-arrival times exponential(lambda); N_t ~ Poisson(lambda*t).",
     ("stochastic_process_foundation", "counting_event_modeling", "substrate_self_knowledge"),
     "stochastic_processes::core_classes", "exponential_inter_arrival", "batch_11"),
    # BATCH 12: functional analysis remainder
    ("T1/bounded_linear_operator", "Bounded linear operator", ("continuous_linear_map",),
     "Linear T: X -> Y with ||T(x)|| <= C ||x|| for some C. Equivalent to continuous for linear maps.",
     ("functional_analysis_foundation", "operator_theory", "substrate_self_knowledge"),
     "functional_analysis::operators", "bounded_implies_continuous_linear", "batch_12"),
    ("T1/compact_operator", "Compact operator", ("limit_of_finite_rank",),
     "T: X -> Y compact iff T maps bounded sets to relatively compact sets. Foundation for spectral theory of compact operators.",
     ("functional_analysis_foundation", "compact_spectral_theory", "substrate_self_knowledge"),
     "functional_analysis::operators", "bounded_to_relatively_compact", "batch_12"),
    ("T1/dual_space", "Dual space", ("X_star", "continuous_linear_functionals"),
     "X^* = space of continuous linear functionals X -> R (or C). Foundation for weak topology + Riesz representation.",
     ("functional_analysis_foundation", "duality_theory", "substrate_self_knowledge"),
     "functional_analysis::duality", "continuous_linear_functionals", "batch_12"),
    ("T1/weak_topology", "Weak topology", ("sigma_X_X_star",),
     "Coarsest topology on X making all continuous linear functionals continuous. Convergence iff <x_n, f> -> <x, f> for all f.",
     ("functional_analysis_foundation", "weak_convergence_theory", "substrate_self_knowledge"),
     "functional_analysis::topology", "induced_by_dual_space", "batch_12"),
    ("T1/sobolev_space", "Sobolev space", ("W_k_p", "weak_derivatives_in_Lp"),
     "Functions with weak derivatives up to order k in L^p. Foundation for PDEs + variational methods.",
     ("functional_analysis_foundation", "PDE_solution_space", "substrate_self_knowledge"),
     "functional_analysis::function_spaces", "weak_derivatives_in_Lp", "batch_12"),
    ("T1/schwartz_space", "Schwartz space", ("rapidly_decreasing_functions",),
     "Smooth functions with all derivatives decaying faster than any polynomial. Foundation for tempered distributions + Fourier analysis.",
     ("functional_analysis_foundation", "fourier_analysis_foundation", "substrate_self_knowledge"),
     "functional_analysis::function_spaces", "all_derivatives_rapid_decay", "batch_12"),
    ("T1/distribution_generalized_function", "Distribution (generalized function)", ("Schwartz_distribution",),
     "Continuous linear functional on Schwartz space. Generalizes functions to include delta, derivatives of L^1, etc.",
     ("functional_analysis_foundation", "generalized_function_theory", "substrate_self_knowledge"),
     "functional_analysis::generalized_functions", "continuous_linear_on_schwartz", "batch_12"),
    ("T1/reflexive_space", "Reflexive space", ("X_eq_X_star_star",),
     "Banach space X with canonical embedding X -> X^** an isomorphism. Foundation for weak compactness.",
     ("functional_analysis_foundation", "double_dual_isomorphism", "substrate_self_knowledge"),
     "functional_analysis::duality", "canonical_into_double_dual_isomorphism", "batch_12"),
    ("T1/separable_space", "Separable space", ("countable_dense_subset",),
     "Topological space containing a countable dense subset. Foundation for L^p (1 <= p < infty) + Hilbert space structure.",
     ("functional_analysis_foundation", "separability_classification", "substrate_self_knowledge"),
     "functional_analysis::topology", "countable_dense_subset", "batch_12"),
    ("T1/hahn_banach_theorem", "Hahn-Banach theorem", ("HB_extension",),
     "Bounded linear functional on subspace extends to whole space preserving norm. Foundation for dual space theory.",
     ("functional_analysis_foundation", "functional_extension", "substrate_self_knowledge"),
     "functional_analysis::core_theorems", "extension_preserving_bound", "batch_12"),
]


def main():
    ps = PartitionedStore(Path("data/substrate_index"))
    print(f"pre-ingest: {len(ps.all_atoms())} atoms\n")
    c = s = f = 0
    for (aid, name, aliases, desc, serves, cat, sig, batch) in SPECS:
        qid = f"math::{aid}"
        if ps.has_atom(qid):
            print(f"SKIP: {qid}"); s += 1; continue
        try:
            atom = Atom(id=aid, name=name, corpus=Corpus.MATH, tier=Tier.TIER_1_FOUNDATIONAL,
                        description=desc, kind=AtomKind.PRIMITIVE, aliases=aliases,
                        metadata={"science_algebra_category": cat, "signature_hint": sig, "batch_origin": batch},
                        serves_capability=serves)
            ps.add_atom(atom, source="t1_algebra_dict_batches_08_to_12_bulk",
                        note=f"per {batch}; T1 math foundation")
            print(f"CREATED: {qid}"); c += 1
        except Exception as e:
            print(f"FAIL: {qid}: {str(e)[:100]}"); f += 1
    print(f"\npost-ingest: {len(ps.all_atoms())}; created={c} skipped={s} failed={f}")


if __name__ == "__main__":
    main()
